# Generated by Django 5.2.17 on 2026-08-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.SlugField(max_length=80)),
                ('chapter_id', models.CharField(max_length=120)),
                ('done', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='portal.learnerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'subject_slug'], name='portal_chap_profile_144218_idx')],
                'unique_together': {('profile', 'subject_slug', 'chapter_id')},
            },
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.SlugField(max_length=80)),
                ('question_id', models.CharField(max_length=64)),
                ('chosen', models.CharField(max_length=1)),
                ('correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='portal.learnerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'subject_slug'], name='portal_prac_profile_c8c0bd_idx')],
            },
        ),
    ]
