# Generated by Django 5.2.17 on 2026-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display label', max_length=120, unique=True)),
                ('api_style', models.CharField(choices=[('openai', 'OpenAI-compatible'), ('anthropic', 'Anthropic')], default='openai', max_length=16)),
                ('base_url', models.CharField(help_text='API root, e.g. https://api.openai.com/v1', max_length=300)),
                ('model_id', models.CharField(help_text='Model id sent to the API', max_length=120)),
                ('api_key', models.CharField(blank=True, help_text='Stored server-side only; masked in UI', max_length=400)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
