# Generated by Django 5.2.17 on 2026-08-27 15:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_aiprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.SlugField(max_length=20)),
                ('mode', models.CharField(default='real', max_length=12)),
                ('status', models.CharField(choices=[('active', 'active'), ('submitted', 'submitted'), ('expired', 'expired')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.JSONField(default=dict)),
                ('sections', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('num_correct', models.IntegerField(null=True)),
                ('num_items', models.IntegerField(null=True)),
                ('score', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='portal.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64)),
                ('block_id', models.CharField(max_length=40)),
                ('chapter_id', models.CharField(blank=True, max_length=120)),
                ('position', models.IntegerField()),
                ('chosen', models.CharField(blank=True, max_length=1)),
                ('correct', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='portal.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.SlugField(max_length=20)),
                ('exam_date', models.DateField()),
                ('weekly_hours', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to='portal.learnerprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['profile', 'exam'], name='portal_exam_profile_b88a14_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['profile', 'status'], name='portal_exam_profile_1c70c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('profile', 'exam'), name='uniq_active_attempt_per_exam'),
        ),
        migrations.AddIndex(
            model_name='examresponse',
            index=models.Index(fields=['attempt', 'correct'], name='portal_exam_attempt_d2b791_idx'),
        ),
        migrations.AddIndex(
            model_name='examresponse',
            index=models.Index(fields=['chapter_id'], name='portal_exam_chapter_b7a7b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresponse',
            unique_together={('attempt', 'position')},
        ),
    ]
