# Generated by Django 5.2.17 on 2026-08-30 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_examattempt_examresponse_studyplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.SlugField(max_length=80)),
                ('card_key', models.CharField(max_length=40)),
                ('front', models.CharField(max_length=400)),
                ('back', models.CharField(blank=True, max_length=600)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('ease', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=0)),
                ('due_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reps', models.IntegerField(default=0)),
                ('lapses', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to='portal.learnerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'due_date'], name='portal_srsc_profile_d3015d_idx')],
                'unique_together': {('profile', 'card_key')},
            },
        ),
    ]
