# Generated by Django 5.2.17 on 2026-08-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_srscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresponse',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=64)),
                ('cause', models.CharField(choices=[('content', 'Content gap'), ('misread', 'Misread the stem'), ('careless', 'Careless slip'), ('trap', 'Trap option')], max_length=12)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='portal.learnerprofile')),
            ],
            options={
                'unique_together': {('profile', 'question_id')},
            },
        ),
    ]
