# Generated by Django 5.2.17 on 2026-10-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_studyplan_target_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='api_style',
            field=models.CharField(choices=[('openai', 'OpenAI-compatible'), ('anthropic', 'Anthropic'), ('claude-code', 'Claude Code CLI (this server)')], default='openai', max_length=16),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='base_url',
            field=models.CharField(blank=True, help_text="API root, e.g. https://api.openai.com/v1 (unused for the Claude Code CLI style — it reuses this server's CC config)", max_length=300),
        ),
    ]
