# Generated by Django 5.2.17 on 2026-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('name_zh', models.CharField(max_length=160)),
                ('short', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SubjectRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('label_zh', models.CharField(max_length=120)),
                ('label_en', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('shared', 'Shared'), ('nmat', 'NMAT unique'), ('mcat', 'MCAT section')], default='shared', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ChapterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.SlugField(max_length=80)),
                ('chapter_title', models.CharField(db_index=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('text_zh', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'ordering': ['subject_slug', 'chapter_title', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['subject_slug', 'chapter_title'], name='knowledge_c_subject_cd4720_idx')],
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.SlugField(max_length=80)),
                ('qid', models.CharField(max_length=64)),
                ('chapter', models.CharField(blank=True, max_length=240)),
                ('q_zh', models.TextField()),
                ('q_en', models.TextField()),
                ('choices', models.JSONField(default=dict)),
                ('answer', models.CharField(max_length=1)),
                ('explain_zh', models.TextField(blank=True)),
                ('explain_en', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['subject_slug', 'sort_order', 'id'],
                'unique_together': {('subject_slug', 'qid')},
            },
        ),
    ]
