# Generated by Django 5.2.17 on 2026-08-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('shared', 'Shared'), ('nmat', 'NMAT unique'), ('mcat', 'MCAT section')], default='shared', max_length=16)),
                ('name', models.CharField(max_length=160)),
                ('name_zh', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='OutlineChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.SlugField(max_length=80)),
                ('group_heading', models.CharField(blank=True, max_length=240)),
                ('title', models.CharField(max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('points', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['subject_slug', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['subject_slug', 'title'], name='knowledge_o_subject_70121c_idx')],
            },
        ),
    ]
