# Generated by Django 5.2.17 on 2026-08-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_curriculumsubject_outlinechapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=16)),
                ('title_zh', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('body_zh', models.TextField()),
                ('body_en', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormulaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.SlugField(max_length=80)),
                ('title_zh', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('formula', models.CharField(max_length=240)),
                ('note_zh', models.TextField(blank=True)),
                ('note_en', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['subject_slug', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120)),
                ('term_zh', models.CharField(blank=True, max_length=120)),
                ('def_zh', models.TextField()),
                ('def_en', models.TextField()),
                ('subjects', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'term'],
            },
        ),
        migrations.CreateModel(
            name='StudyPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.SlugField(max_length=80, unique=True)),
                ('title_zh', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('blurb_zh', models.TextField()),
                ('blurb_en', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
