from django.contrib import admin
from django.urls import path

from portal import accounts, coach_admin, coach_insights, dashboard, exam_views, views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", accounts.login_view, name="login"),
    path("register/", accounts.register_view, name="register"),
    path("logout/", accounts.logout_view, name="logout"),
    path("account/", accounts.account_view, name="account"),
    path("account/password/", accounts.password_change_view, name="password_change"),
    path("manage/users/", accounts.manage_users, name="manage_users"),
    path(
        "manage/users/<int:user_id>/",
        accounts.manage_user_action,
        name="manage_user_action",
    ),
    path("manage/models/", coach_admin.manage_models, name="manage_models"),
    path(
        "manage/models/<int:provider_id>/",
        coach_admin.manage_model_action,
        name="manage_model_action",
    ),
    path("study/", views.study_hub, name="study_hub"),
    path("strategy/", views.strategy_library, name="strategy_library"),
    path("materials/", views.materials_hub, name="materials_hub"),
    path("materials/glossary/", views.materials_glossary, name="materials_glossary"),
    path("materials/formulas/<slug:slug>/", views.materials_formulas, name="materials_formulas"),
    path("materials/tips/", views.materials_tips, name="materials_tips"),
    path("materials/checklists/", views.materials_checklists, name="materials_checklists"),
    path("api/study/", views.study_api, name="study_api"),
    path("api/progress/", views.progress_api, name="progress_api"),
    path("api/progress/update/", views.progress_update_api, name="progress_update_api"),
    path("api/practice/attempt/", views.practice_attempt_api, name="practice_attempt_api"),
    path("practice/", views.practice_hub, name="practice_hub"),
    path("practice/<slug:slug>/", views.practice_detail, name="practice_detail"),
    path("subjects/", views.subject_list, name="subject_list"),
    path("subjects/<slug:slug>/", views.subject_detail, name="subject_detail"),
    path("content-images/<path:path>", views.content_image, name="content_image"),
    path("learn/<slug:project>/<slug:unit_key>/", views.unit_detail, name="unit_detail"),
    path(
        "tutorials/<slug:slug>/<str:chapter_id>/",
        views.tutorial_detail,
        name="tutorial_detail",
    ),
    path(
        "tutorials/<slug:slug>/<str:chapter_id>/drill/",
        views.tutorial_drill,
        name="tutorial_drill",
    ),
    path(
        "tutorials/<slug:slug>/<str:chapter_id>/pdf/",
        views.tutorial_pdf,
        name="tutorial_pdf",
    ),
    path("nmat/", views.nmat_hub, name="nmat_hub"),
    path("nmat/<slug:slug>/", views.nmat_subject, name="nmat_subject"),
    path("mcat/", views.mcat_hub, name="mcat_hub"),
    path("mcat/<slug:slug>/", views.mcat_section, name="mcat_section"),
    path("diseases/", views.disease_list, name="disease_list"),
    path("diseases/<slug:slug>/", views.disease_detail, name="disease_detail"),
    # ---- mock-exam engine ----
    path("exams/", exam_views.exam_list, name="exam_list"),
    path("exams/<slug:exam_id>/", exam_views.exam_detail, name="exam_detail"),
    path("exams/<slug:exam_id>/start/", exam_views.exam_start, name="exam_start"),
    path("exams/<slug:exam_id>/take/<int:attempt_id>/", exam_views.exam_take, name="exam_take"),
    path("exams/<slug:exam_id>/take/<int:attempt_id>/<slug:block_id>/<int:pos>/",
         exam_views.exam_question, name="exam_question"),
    path("exams/<slug:exam_id>/break/<int:attempt_id>/<slug:block_id>/",
         exam_views.exam_break, name="exam_break"),
    path("exams/<slug:exam_id>/begin/<int:attempt_id>/<slug:block_id>/",
         exam_views.exam_begin, name="exam_begin"),
    path("exams/<slug:exam_id>/finish/<int:attempt_id>/<slug:block_id>/",
         exam_views.exam_finish_block, name="exam_finish_block"),
    path("exams/api/answer/", exam_views.exam_answer_api, name="exam_answer_api"),
    path("exams/api/submit/", exam_views.exam_submit_api, name="exam_submit_api"),
    path("exams/result/<int:attempt_id>/", exam_views.exam_result, name="exam_result"),
    # ---- study platform ----
    path("dashboard/", dashboard.dashboard, name="dashboard"),
    path("review/", dashboard.review, name="review"),
    path("review/redo/<slug:chapter_id>/", dashboard.review_redo, name="review_redo"),
    path("api/review/cause/", dashboard.review_cause_api, name="review_cause_api"),
    path("plan/", dashboard.plan, name="plan"),
    path("flashcards/", exam_views.flashcards_hub, name="flashcards_hub"),
    path("scores/", views.score_interpreter, name="score_interpreter"),
    path("coach/insights/", coach_insights.coach_insights, name="coach_insights"),
    path("api/flashcards/grade/", exam_views.flashcard_grade_api, name="flashcard_grade_api"),
    path("plan/save/", dashboard.plan_save, name="plan_save"),
    path("admin/", admin.site.urls),
]
