"""One-off export: dump the live knowledge DB into the content/ YAML tree.

Sources of truth:
  * the live knowledge sqlite (subjects, notes, practice, glossary, formulas,
    tips, paths, diseases, subject refs) — exactly what pages render today
  * portal.notes' raw literal replayed through the merge functions for the
    CANONICAL (pre-overlay) note buckets; the cross-subject overlay copies are
    regenerated by portal/content.py at read time
  * materials_data.CHECKLISTS and the enriched exam hubs (never DB rows)

Bakes bilingual.enrich_* output into the files, so the *_en fields become
data instead of render-time lexicon lookups. Writes content/MANIFEST.json
for validate_content. Run once; delete after the migration settles.
"""

from __future__ import annotations

import ast
import hashlib
import json
import subprocess
from pathlib import Path

import yaml
from django.core.management.base import BaseCommand

from knowledge.models import (
    ChapterNote,
    CurriculumSubject,
    DiseaseArticle,
    ExamTip,
    FormulaEntry,
    GlossaryTerm,
    PracticeQuestion,
    StudyPath,
    SubjectRef,
)
from portal import exams, materials_data, notes as notes_mod
from portal.bilingual import enrich_subject

CONTENT = Path(__file__).resolve().parents[3] / "content"

# fields whose enriched flat <k>/<k>_en pair becomes a {zh, en} mapping
PAIR_KEYS = ("summary", "focus", "nmat_role", "mcat_role", "source_note", "format")


def pair(zh, en):
    return zh if zh == en else {"zh": zh, "en": en}


def dump(path: str, doc: dict) -> None:
    file = CONTENT / path
    file.parent.mkdir(parents=True, exist_ok=True)
    text = yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, width=100)
    assert yaml.safe_load(text) == doc, f"roundtrip failed for {file}"
    file.write_text(text, encoding="utf-8")


def canonical_notes() -> dict[str, dict]:
    """Pre-overlay merged buckets: raw NOTES literal + the two merge packs."""
    source = Path(notes_mod.__file__).read_text(encoding="utf-8")
    tree = ast.parse(source)

    def _target_id(node):
        if isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name):
            return node.targets[0].id
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            return node.target.id
        return None

    literal = next(
        node.value
        for node in tree.body
        if _target_id(node) == "NOTES" and isinstance(node.value, ast.Dict)
    )
    raw = ast.literal_eval(literal)
    from portal.extra_notes import merge_notes
    from portal.pack_enrich import merge_note_pack

    return merge_note_pack(merge_notes(raw))


def subject_doc(row: CurriculumSubject) -> dict:
    """Enriched subject dict → canonical YAML document."""
    enriched = enrich_subject(row.as_dict())
    for group in enriched.get("chapters") or []:
        for item in group.get("items") or []:
            item.pop("chapter_id", None)
            item.pop("study_notes", None)
    doc = {}
    for key, value in enriched.items():
        if key in ("label_zh", "label_en"):
            continue
        if key.endswith("_en"):
            continue
        if key in PAIR_KEYS:
            doc[key] = pair(value, enriched.get(f"{key}_en", value))
        elif key == "exam_notes" and isinstance(value, dict):
            doc[key] = {
                exam: pair(text, enriched.get("exam_notes_en", {}).get(exam, text))
                for exam, text in value.items()
            }
        elif key == "chapters":
            doc[key] = [
                {
                    **{k: v for k, v in g.items() if k not in ("heading", "items", "heading_en")},
                    "heading": pair(g.get("heading", ""), g.get("heading_en", g.get("heading", ""))),
                    "items": [
                        {
                            **{
                                k: v
                                for k, v in it.items()
                                if k not in ("title", "points", "title_en", "points_en")
                            },
                            "title": pair(it.get("title", ""), it.get("title_en", it.get("title", ""))),
                            "points": [
                                pair(a, b)
                                for a, b in zip(
                                    it.get("points") or [], it.get("points_en") or []
                                )
                            ],
                        }
                        for it in g.get("items") or []
                    ],
                }
                for g in value
            ]
        else:
            doc[key] = value
    doc["kind"] = row.kind
    return doc


def exam_doc(exam: dict, part1_refs: list[str] | None, section_refs: list[str] | None) -> dict:
    doc: dict = {}
    for key, value in exam.items():
        if key in ("parts", "sections", "format", "format_en", "discipline_mix_note",
                   "discipline_mix_note_en"):
            continue
        doc[key] = value
    if "format" in exam:
        doc["format"] = pair(exam["format"], exam.get("format_en", exam["format"]))
    if "discipline_mix_note" in exam:
        doc["discipline_mix_note"] = pair(
            exam["discipline_mix_note"],
            exam.get("discipline_mix_note_en", exam["discipline_mix_note"]),
        )
    if part1_refs is not None:
        parts = []
        for part in exam["parts"]:
            entry = {
                k: v for k, v in part.items() if k not in ("subjects", "name_en")
            }
            if part.get("id") == "part1":
                entry["subject_refs"] = part1_refs
                entry.pop("subjects", None)
            else:
                entry["subjects"] = [
                    subject_inline(s) for s in part.get("subjects") or []
                ]
            parts.append(entry)
        doc["parts"] = parts
    if section_refs is not None:
        doc["section_refs"] = section_refs
    return doc


def subject_inline(subject: dict) -> dict:
    """NMAT part-2 link entries (not CurriculumSubjects)."""
    out = {}
    for key, value in subject.items():
        if key in ("label_zh", "label_en") or key.endswith("_en"):
            continue
        if key in PAIR_KEYS:
            out[key] = pair(value, subject.get(f"{key}_en", value))
        else:
            out[key] = value
    return out


class Command(BaseCommand):
    help = "Export the live knowledge DB into content/ YAML files (one-off)."

    def handle(self, *args, **options):
        if not CONTENT.exists():
            CONTENT.mkdir(parents=True)

        # --- subjects -----------------------------------------------------
        rows = list(CurriculumSubject.objects.all())  # Meta order: kind, slug
        kinds: dict[str, list[str]] = {}
        for row in rows:
            kinds.setdefault(row.kind, []).append(row.slug)
            dump(f"subjects/{row.slug}.yml", subject_doc(row))

        # --- notes (canonical, pre-overlay) --------------------------------
        canon = canonical_notes()
        note_counts = {}
        for slug in sorted(canon):
            bucket = canon[slug]
            dump(
                f"notes/{slug}.yml",
                {
                    "slug": slug,
                    "chapters": [
                        {"title": title, "bullets": bullets}
                        for title, bullets in bucket.items()
                    ],
                },
            )
            note_counts[slug] = sum(len(v) for v in bucket.values())

        # --- practice -------------------------------------------------------
        practice_by_slug: dict[str, list] = {}
        for q in PracticeQuestion.objects.all().order_by("subject_slug", "sort_order", "id"):
            practice_by_slug.setdefault(q.subject_slug, []).append(
                {
                    "id": q.qid,
                    "q": pair(q.q_zh, q.q_en),
                    "choices": {k: dict(v) for k, v in (q.choices or {}).items()},
                    "answer": q.answer,
                    "explain": pair(q.explain_zh, q.explain_en),
                    "chapter": q.chapter,
                }
            )
        for slug, items in practice_by_slug.items():
            dump(f"practice/{slug}.yml", {"slug": slug, "items": items})

        # --- materials ------------------------------------------------------
        glossary = [
            {
                "term": g.term,
                "term_zh": g.term_zh,
                "def": pair(g.def_zh, g.def_en),
                "subjects": list(g.subjects or []),
            }
            for g in GlossaryTerm.objects.all().order_by("sort_order", "term")
        ]
        dump("materials/glossary.yml", {"terms": glossary})

        formula_sheets: dict[str, list] = {}
        for f in FormulaEntry.objects.all().order_by("subject_slug", "sort_order", "id"):
            formula_sheets.setdefault(f.subject_slug, []).append(
                {
                    "title": pair(f.title_zh, f.title_en),
                    "formula": f.formula,
                    "note": pair(f.note_zh, f.note_en),
                }
            )
        dump(
            "materials/formulas.yml",
            {
                "sheets": [
                    {"slug": slug, "entries": entries}
                    # FORMULAS dict key order = formula_catalog display order
                    for slug in materials_data.FORMULAS
                    for entries in [formula_sheets.get(slug, [])]
                ]
            },
        )

        tips = [
            {
                "exam": t.exam,
                "title": pair(t.title_zh, t.title_en),
                "body": pair(t.body_zh, t.body_en),
            }
            for t in ExamTip.objects.all().order_by("sort_order", "id")
        ]
        dump("materials/tips.yml", {"tips": tips})

        paths = [
            {
                "id": p.path_id,
                "title": pair(p.title_zh, p.title_en),
                "blurb": pair(p.blurb_zh, p.blurb_en),
                "steps": [
                    {"zh": s.get("label_zh", ""), "en": s.get("label_en", ""), "href": s.get("href", "")}
                    for s in (p.steps or [])
                ],
            }
            for p in StudyPath.objects.all().order_by("sort_order", "id")
        ]
        dump("materials/paths.yml", {"paths": paths})

        checklists = [
            {
                "id": c["id"],
                "exam": c["exam"],
                "title": pair(c["title_zh"], c["title_en"]),
                "items": [
                    pair(zh, en)
                    for zh, en in zip(c.get("items_zh") or [], c.get("items_en") or [])
                ],
            }
            for c in materials_data.CHECKLISTS
        ]
        dump("materials/checklists.yml", {"checklists": checklists})

        # --- diseases ---------------------------------------------------------
        for d in DiseaseArticle.objects.all().order_by("slug"):
            data = d.as_dict()
            data.pop("updated_at", None)
            dump(f"diseases/{d.slug}.yml", data)

        # --- catalog + exam hubs ---------------------------------------------
        labels = {
            ref.slug: {"zh": ref.label_zh, "en": ref.label_en}
            for ref in SubjectRef.objects.all().order_by("slug")
        }
        dump(
            "catalog.yml",
            {
                "kinds": kinds,
                "formula_slugs": list(materials_data.FORMULAS),
                "labels": labels,
            },
        )
        dump(
            "exams/nmat.yml",
            exam_doc(exams.nmat_exam(), part1_refs=kinds.get("nmat", []), section_refs=None),
        )
        dump(
            "exams/mcat.yml",
            exam_doc(exams.mcat_exam(), part1_refs=None, section_refs=kinds.get("mcat", [])),
        )

        # --- manifest -----------------------------------------------------------
        # counts come from the reader itself, so validate_content (which also
        # reads through the reader) compares like with like.
        from portal import content as content_reader

        content_reader._cache = None
        content_reader._cache_stamp = None
        store = content_reader.store()
        rev = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=CONTENT.parent,
        ).stdout.strip() or "unknown"
        manifest = {
            "source_rev": rev,
            "counts": {
                "subjects": len(store["subjects"]),
                "note_buckets": sum(len(v) for v in store["notes"].values()),
                "note_bullets": sum(
                    len(b) for v in store["notes"].values() for b in v.values()
                ),
                "practice": sum(len(v) for v in store["practice"].values()),
                "glossary": len(store["glossary"]),
                "formulas": sum(len(v) for v in store["formulas"].values()),
                "tips": len(store["tips"]),
                "paths": len(store["paths"]),
                "checklists": len(store["checklists"]),
                "diseases": len(store["diseases"]),
            },
            "files": {
                str(p.relative_to(CONTENT)): hashlib.sha256(p.read_bytes()).hexdigest()
                for p in sorted(CONTENT.rglob("*.yml"))
            },
        }
        (CONTENT / "MANIFEST.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )

        self.stdout.write(self.style.SUCCESS(f"exported to {CONTENT}"))
        for key, count in manifest["counts"].items():
            self.stdout.write(f"  {key}: {count}")
