"""Additional high-yield practice items to extend static banks."""

from __future__ import annotations

import copy

EXTRA_PRACTICE: dict[str, list[dict]] = {
    "biology": [
        {
            "id": "bio-5",
            "q_zh": "主动运输与简单扩散的主要区别是：",
            "q_en": "Active transport differs from simple diffusion mainly because it:",
            "choices": {
                "A": {"zh": "沿浓度梯度、不需能量", "en": "Moves down a gradient without energy"},
                "B": {"zh": "可逆浓度梯度并消耗 ATP（或电化学梯度）", "en": "Can move against a gradient using ATP (or an electrochemical gradient)"},
                "C": {"zh": "只通过核孔", "en": "Occurs only through nuclear pores"},
                "D": {"zh": "只运输气体", "en": "Transports only gases"},
            },
            "answer": "B",
            "explain_zh": "主动运输需要载体/泵并消耗能量；简单扩散顺浓度梯度、不需代谢能。",
            "explain_en": "Active transport uses carriers/pumps and energy; simple diffusion follows a gradient without metabolic energy.",
            "chapter": "Cells and Cellular Processes",
        },
        {
            "id": "bio-6",
            "q_zh": "孟德尔分离定律的核心含义是：",
            "q_en": "Mendel’s law of segregation states that:",
            "choices": {
                "A": {"zh": "同源染色体上的等位基因在配子形成时分离", "en": "Alleles of a gene separate into gametes during gamete formation"},
                "B": {"zh": "所有基因永远连锁", "en": "All genes are permanently linked"},
                "C": {"zh": "显性等位基因会消失", "en": "Dominant alleles disappear"},
                "D": {"zh": "配子总是二倍体", "en": "Gametes are always diploid"},
            },
            "answer": "A",
            "explain_zh": "减数分裂使每对等位基因进入不同配子，恢复单倍体。",
            "explain_en": "Meiosis puts one allele of each pair into each gamete, restoring haploidy.",
            "chapter": "Genetics",
        },
        {
            "id": "bio-7",
            "q_zh": "胰岛素升高血糖还是降低血糖？",
            "q_en": "Insulin raises or lowers blood glucose?",
            "choices": {
                "A": {"zh": "升高", "en": "Raises it"},
                "B": {"zh": "降低（促进细胞摄取与储存）", "en": "Lowers it (promotes uptake and storage)"},
                "C": {"zh": "对血糖无影响", "en": "Has no effect on glucose"},
                "D": {"zh": "只影响血钙", "en": "Affects only blood calcium"},
            },
            "answer": "B",
            "explain_zh": "胰岛素促进葡萄糖进入细胞并促进糖原/脂肪合成，从而降低血糖。",
            "explain_en": "Insulin drives glucose into cells and promotes glycogen/fat synthesis, lowering blood glucose.",
            "chapter": "Life Processes: Regulation and Homeostasis",
        },
        {
            "id": "bio-8",
            "q_zh": "食物网比食物链更能反映生态系统的什么特征？",
            "q_en": "A food web better reflects an ecosystem’s:",
            "choices": {
                "A": {"zh": "单一线性取食路径", "en": "Single linear feeding path"},
                "B": {"zh": "多物种间复杂取食关系", "en": "Complex feeding links among many species"},
                "C": {"zh": "能量完全循环无损失", "en": "Energy cycling with no loss"},
                "D": {"zh": "所有营养级生物量相等", "en": "Equal biomass at every trophic level"},
            },
            "answer": "B",
            "explain_zh": "大多数物种参与多条取食关系；食物网比单链更接近现实。",
            "explain_en": "Most species participate in multiple feeding links; webs are more realistic than single chains.",
            "chapter": "Organisms and Their Environment",
        },
        {
            "id": "bio-9",
            "q_zh": "有丝分裂结束时，子细胞染色体数目相对母细胞：",
            "q_en": "After mitosis, daughter cells have chromosome number:",
            "choices": {
                "A": {"zh": "减半", "en": "Halved"},
                "B": {"zh": "与母细胞相同（二倍体维持）", "en": "The same as the parent (diploidy maintained)"},
                "C": {"zh": "变为四倍体", "en": "Quadrupled"},
                "D": {"zh": "随机变化", "en": "Randomly variable"},
            },
            "answer": "B",
            "explain_zh": "有丝分裂复制后均分，产生遗传相同的二倍体子细胞。",
            "explain_en": "Mitosis duplicates then evenly partitions chromosomes, yielding genetically identical diploid daughters.",
            "chapter": "2C · Cell division, differentiation, specialization",
        },
        {
            "id": "bio-10",
            "q_zh": "原核生物与病毒相比，原核细胞通常具有：",
            "q_en": "Compared with viruses, prokaryotic cells typically have:",
            "choices": {
                "A": {"zh": "核糖体与可独立代谢的胞质", "en": "Ribosomes and cytoplasm capable of independent metabolism"},
                "B": {"zh": "膜包被的细胞核", "en": "A membrane-bound nucleus"},
                "C": {"zh": "只能在宿主内复制", "en": "Replication only inside a host"},
                "D": {"zh": "没有遗传物质", "en": "No genetic material"},
            },
            "answer": "A",
            "explain_zh": "原核细胞是独立生命体；病毒需宿主细胞复制且非完整细胞结构。",
            "explain_en": "Prokaryotes are free-living cells; viruses depend on host machinery and lack full cellular organization.",
            "chapter": "2B · Prokaryotes and viruses",
        },
        {
            "id": "bio-11",
            "q_zh": "胚胎发育中细胞分化主要意味着：",
            "q_en": "Cell differentiation during development mainly means:",
            "choices": {
                "A": {"zh": "基因组被随机删除", "en": "The genome is randomly deleted"},
                "B": {"zh": "不同细胞类型选择性表达不同基因", "en": "Different cell types selectively express different genes"},
                "C": {"zh": "所有细胞功能完全相同", "en": "All cells become functionally identical"},
                "D": {"zh": "停止所有蛋白质合成", "en": "All protein synthesis stops"},
            },
            "answer": "B",
            "explain_zh": "分化通过基因表达调控实现，而非改变 DNA 序列（体细胞克隆除外）。",
            "explain_en": "Differentiation arises from regulated gene expression, not wholesale DNA change (except somatic mutations).",
            "chapter": "Development",
        },
        {
            "id": "bio-12",
            "q_zh": "神经元动作电位“全或无”特性是指：",
            "q_en": "The “all-or-none” property of a neuronal action potential means:",
            "choices": {
                "A": {"zh": "刺激越强，单个动作电位幅度越大", "en": "Stronger stimuli produce larger single action potentials"},
                "B": {"zh": "达到阈值则产生固定幅度脉冲，否则不产生", "en": "At threshold a fixed-size spike occurs; below threshold, none"},
                "C": {"zh": "神经元永不兴奋", "en": "Neurons never fire"},
                "D": {"zh": "突触传递不需要递质", "en": "Synaptic transmission needs no neurotransmitter"},
            },
            "answer": "B",
            "explain_zh": "单个动作电位幅度恒定；刺激强度影响频率而非单次幅度。",
            "explain_en": "Single spike amplitude is constant; stimulus strength mainly affects firing frequency.",
            "chapter": "3A · Nervous & endocrine coordination",
        },
    ],
    "chemistry": [
        {
            "id": "chem-5",
            "q_zh": "下列哪种溶液 pH 最接近 7（25 °C）？",
            "q_en": "Which solution has a pH closest to 7 at 25 °C?",
            "choices": {
                "A": {"zh": "0.1 M HCl", "en": "0.1 M HCl"},
                "B": {"zh": "0.1 M NaOH", "en": "0.1 M NaOH"},
                "C": {"zh": "纯水", "en": "Pure water"},
                "D": {"zh": "浓硫酸", "en": "Concentrated sulfuric acid"},
            },
            "answer": "C",
            "explain_zh": "中性水 pH = 7；强酸强碱溶液远离 7。",
            "explain_en": "Neutral water has pH 7; strong acid/base solutions are far from 7.",
            "chapter": "General Chemistry",
        },
        {
            "id": "chem-6",
            "q_zh": "碳在有机化学中常呈四价，主要因为：",
            "q_en": "Carbon is tetravalent in organic chemistry mainly because it:",
            "choices": {
                "A": {"zh": "有 4 个价电子，可形成 4 个共价键", "en": "Has 4 valence electrons and forms 4 covalent bonds"},
                "B": {"zh": "只能形成离子键", "en": "Forms only ionic bonds"},
                "C": {"zh": "原子核带负电", "en": "Its nucleus is negatively charged"},
                "D": {"zh": "不能形成双键", "en": "Cannot form double bonds"},
            },
            "answer": "A",
            "explain_zh": "碳的 sp³/sp²/sp 杂化使其可单、双、三键连接，构成有机骨架。",
            "explain_en": "Carbon’s hybridization allows single, double, and triple bonds that scaffold organic molecules.",
            "chapter": "Organic Chemistry",
        },
        {
            "id": "chem-7",
            "q_zh": "滴定终点最接近：",
            "q_en": "The titration endpoint is closest to:",
            "choices": {
                "A": {"zh": "指示剂变色的实验点", "en": "The experimental point where indicator color changes"},
                "B": {"zh": "溶液体积为零", "en": "Zero solution volume"},
                "C": {"zh": "反应永远不发生", "en": "A reaction that never occurs"},
                "D": {"zh": "样品质量加倍", "en": "Doubling sample mass"},
            },
            "answer": "A",
            "explain_zh": "终点由指示剂或仪器信号判定；化学计量点（当量点）是理论等量点，二者应尽量接近。",
            "explain_en": "The endpoint is signaled by indicator/instrument; the equivalence point is theoretical—they should be close.",
            "chapter": "Analytical Chemistry",
        },
        {
            "id": "chem-8",
            "q_zh": "水的氢键对其高比热容的主要贡献是：",
            "q_en": "Hydrogen bonding in water mainly contributes to its high specific heat by:",
            "choices": {
                "A": {"zh": "吸收热量打断氢键而不大幅升温", "en": "Absorbing heat to break H-bonds without large temperature rise"},
                "B": {"zh": "使水在 0 °C 沸腾", "en": "Making water boil at 0 °C"},
                "C": {"zh": "消除分子间作用", "en": "Eliminating intermolecular forces"},
                "D": {"zh": "使水成为强电解质", "en": "Making water a strong electrolyte"},
            },
            "answer": "A",
            "explain_zh": "氢键网络储存热能，缓冲温度变化——对生命系统重要。",
            "explain_en": "The H-bond network stores thermal energy, buffering temperature swings—critical for life.",
            "chapter": "5A · Water and its solutions",
        },
        {
            "id": "chem-9",
            "q_zh": "升高温度对吸热反应的平衡常数 K 通常：",
            "q_en": "Raising temperature on an endothermic reaction typically:",
            "choices": {
                "A": {"zh": "使 K 增大", "en": "Increases K"},
                "B": {"zh": "使 K 减小", "en": "Decreases K"},
                "C": {"zh": "使 K 恒为 1", "en": "Fixes K at 1"},
                "D": {"zh": "与 K 无关", "en": "Has no relation to K"},
            },
            "answer": "A",
            "explain_zh": "吸热反应加热有利于产物，K 增大；放热反应则相反。",
            "explain_en": "Heating favors products in endothermic reactions (K rises); exothermic reactions show the opposite.",
            "chapter": "5E · Chemical thermodynamics and kinetics",
        },
        {
            "id": "chem-10",
            "q_zh": "肽键在蛋白质中的主要性质是：",
            "q_en": "The peptide bond in proteins is mainly characterized by:",
            "choices": {
                "A": {"zh": "部分双键性、平面刚性", "en": "Partial double-bond character and planarity"},
                "B": {"zh": "极易在生理 pH 自发断裂", "en": "Spontaneous cleavage at physiological pH"},
                "C": {"zh": "只连接脂质", "en": "Linking only lipids"},
                "D": {"zh": "不含氮原子", "en": "Containing no nitrogen"},
            },
            "answer": "A",
            "explain_zh": "肽键共振使其呈平面、旋转受限，决定蛋白质主链构象。",
            "explain_en": "Resonance gives the peptide bond planarity and restricted rotation, shaping the protein backbone.",
            "chapter": "Biochemistry",
        },
    ],
    "physics": [
        {
            "id": "phy-5",
            "q_zh": "物体在匀速圆周运动中，向心加速度方向：",
            "q_en": "In uniform circular motion, centripetal acceleration points:",
            "choices": {
                "A": {"zh": "沿切线、与速度同向", "en": "Tangent to the path, same as velocity"},
                "B": {"zh": "指向圆心", "en": "Toward the center of the circle"},
                "C": {"zh": "背离圆心", "en": "Away from the center"},
                "D": {"zh": "为零", "en": "Is zero"},
            },
            "answer": "B",
            "explain_zh": "向心加速度改变速度方向；速度沿切线，加速度指向圆心。",
            "explain_en": "Centripetal acceleration changes velocity direction; velocity is tangential, acceleration points inward.",
            "chapter": "Mechanics",
        },
        {
            "id": "phy-6",
            "q_zh": "理想气体在等温膨胀时，内能变化 ΔU 为：",
            "q_en": "For an ideal gas undergoing isothermal expansion, ΔU equals:",
            "choices": {
                "A": {"zh": "正值且很大", "en": "A large positive value"},
                "B": {"zh": "零（理想气体内能只取决于温度）", "en": "Zero (ideal-gas internal energy depends only on temperature)"},
                "C": {"zh": "负无穷", "en": "Negative infinity"},
                "D": {"zh": "等于压强", "en": "Equals pressure"},
            },
            "answer": "B",
            "explain_zh": "理想气体内能是温度的函数；等温过程温度不变故 ΔU = 0。",
            "explain_en": "Ideal-gas internal energy is a function of T; isothermal means ΔU = 0.",
            "chapter": "Thermodynamics",
        },
        {
            "id": "phy-7",
            "q_zh": "光从空气进入玻璃时，一般：",
            "q_en": "When light goes from air into glass, it generally:",
            "choices": {
                "A": {"zh": "速率增大、波长变长", "en": "Speeds up with longer wavelength"},
                "B": {"zh": "速率减小、向法线偏折（折射）", "en": "Slows and bends toward the normal (refraction)"},
                "C": {"zh": "不发生折射", "en": "Does not refract"},
                "D": {"zh": "频率改变", "en": "Changes frequency"},
            },
            "answer": "B",
            "explain_zh": "进入光密介质速度降低；折射角小于入射角（向法线偏折）。",
            "explain_en": "Light slows in a denser medium; the refracted ray bends toward the normal.",
            "chapter": "Vibrations, Waves, and Optics",
        },
        {
            "id": "phy-8",
            "q_zh": "并联电路中各支路电压关系是：",
            "q_en": "In a parallel circuit, the voltage across each branch:",
            "choices": {
                "A": {"zh": "相同", "en": "Is the same"},
                "B": {"zh": "与电阻成正比", "en": "Is proportional to resistance"},
                "C": {"zh": "总是为零", "en": "Is always zero"},
                "D": {"zh": "随机分布", "en": "Is random"},
            },
            "answer": "A",
            "explain_zh": "并联元件两端电势差相同；总电流分流各支。",
            "explain_en": "Parallel elements share the same potential difference; total current splits among branches.",
            "chapter": "Electricity and Magnetism",
        },
        {
            "id": "phy-9",
            "q_zh": "光电效应说明光具有：",
            "q_en": "The photoelectric effect shows that light has:",
            "choices": {
                "A": {"zh": "波动性但无粒子性", "en": "Wave nature only, no particle nature"},
                "B": {"zh": "量子化能量（光子）", "en": "Quantized energy (photons)"},
                "C": {"zh": "与频率无关的能量", "en": "Energy independent of frequency"},
                "D": {"zh": "无限大的波长", "en": "Infinitely long wavelength"},
            },
            "answer": "B",
            "explain_zh": "只有当 hf 超过逸出功才发射电子；经典波动理论无法解释截止频率。",
            "explain_en": "Electrons emit only when hf exceeds the work function; classical waves cannot explain a cutoff frequency.",
            "chapter": "Modern Physics",
        },
        {
            "id": "phy-10",
            "q_zh": "根据伯努利原理（理想、定常、不可压缩流），管径缩小处：",
            "q_en": "By Bernoulli’s principle (ideal, steady, incompressible flow), where a pipe narrows:",
            "choices": {
                "A": {"zh": "流速增大、静压降低", "en": "Speed rises and static pressure drops"},
                "B": {"zh": "流速降低、静压升高", "en": "Speed falls and static pressure rises"},
                "C": {"zh": "流速与压力均不变", "en": "Both speed and pressure stay constant"},
                "D": {"zh": "密度必须为零", "en": "Density must be zero"},
            },
            "answer": "A",
            "explain_zh": "连续性方程 A v = 常数 → 窄处流速大；伯努利 → 动能增则静压降。",
            "explain_en": "Continuity (Av = constant) raises speed in a narrow region; Bernoulli links higher speed to lower static pressure.",
            "chapter": "4B · Fluids, circulation, gas exchange",
        },
    ],
    "behavioral-social": [
        {
            "id": "beh-4",
            "q_zh": "短时记忆的容量与持续时间大致是：",
            "q_en": "Short-term memory capacity and duration are roughly:",
            "choices": {
                "A": {"zh": "无限容量、终生保持", "en": "Unlimited capacity, lifelong"},
                "B": {"zh": "有限容量（约 7±2 组块）、秒到分钟级", "en": "Limited (~7±2 chunks), seconds to a minute"},
                "C": {"zh": "只有视觉、无听觉", "en": "Visual only, no auditory"},
                "D": {"zh": "与长时记忆完全相同", "en": "Identical to long-term memory"},
            },
            "answer": "B",
            "explain_zh": "STM 容量小、保持短；复述与组块可延长保持。",
            "explain_en": "STM holds few chunks briefly; rehearsal and chunking extend retention.",
            "chapter": "Psychology",
        },
        {
            "id": "beh-5",
            "q_zh": "社会规范与法律的主要区别是：",
            "q_en": "Social norms differ from laws mainly because norms:",
            "choices": {
                "A": {"zh": "由群体共享期待维系，未必有正式制裁", "en": "Are shared group expectations, not always formally enforced"},
                "B": {"zh": "只适用于个人内心", "en": "Apply only inside one person’s mind"},
                "C": {"zh": "永远比法律更宽松", "en": "Are always looser than laws"},
                "D": {"zh": "与行为无关", "en": "Are unrelated to behavior"},
            },
            "answer": "A",
            "explain_zh": "规范靠社会化与舆论维系；法律有正式制定与强制力。",
            "explain_en": "Norms rely on socialization and informal sanction; laws are codified with formal enforcement.",
            "chapter": "Sociology and Anthropology",
        },
        {
            "id": "beh-6",
            "q_zh": "知觉组织中的“图形-背景”原则指：",
            "q_en": "Figure–ground organization in perception means:",
            "choices": {
                "A": {"zh": "把刺激分为突出的对象与较不突出的背景", "en": "Splitting a scene into a salient object and a less salient background"},
                "B": {"zh": "否认深度知觉", "en": "Denying depth perception"},
                "C": {"zh": "只处理听觉", "en": "Processing only audition"},
                "D": {"zh": "所有刺激同等突出", "en": "All stimuli are equally salient"},
            },
            "answer": "A",
            "explain_zh": "知觉系统倾向将一部分组织为“图形”、其余退为背景。",
            "explain_en": "The perceptual system tends to organize one region as figure and the rest as ground.",
            "chapter": "FC6 · Perceive, think, react",
        },
        {
            "id": "beh-7",
            "q_zh": "认知失调理论预测：态度与行为不一致时，人们常：",
            "q_en": "Cognitive dissonance theory predicts that when attitudes and behavior clash, people often:",
            "choices": {
                "A": {"zh": "改变态度或重新解释行为以减少不适", "en": "Change attitudes or reinterpret behavior to reduce discomfort"},
                "B": {"zh": "永久丧失记忆", "en": "Permanently lose memory"},
                "C": {"zh": "只增加生理唤醒而无心理变化", "en": "Only increase arousal with no psychological change"},
                "D": {"zh": "必然承认错误", "en": "Always admit error immediately"},
            },
            "answer": "A",
            "explain_zh": "不一致产生心理不适，动机驱使态度/信念调整以恢复一致。",
            "explain_en": "Inconsistency is aversive, motivating attitude/belief shifts to restore consistency.",
            "chapter": "FC7 · Behavior and behavior change",
        },
        {
            "id": "beh-8",
            "q_zh": "旁观者效应是指：",
            "q_en": "The bystander effect is:",
            "choices": {
                "A": {"zh": "在场他人越多，个体提供帮助的可能性越低", "en": "More bystanders lower the chance any one person helps"},
                "B": {"zh": "独处时从不助人", "en": "People never help when alone"},
                "C": {"zh": "只影响听觉注意", "en": "Affects only auditory attention"},
                "D": {"zh": "与责任扩散无关", "en": "Unrelated to diffusion of responsibility"},
            },
            "answer": "A",
            "explain_zh": "责任分散与多元无知降低干预率；明确责任可减弱该效应。",
            "explain_en": "Diffusion of responsibility and pluralistic ignorance reduce helping; clear responsibility weakens the effect.",
            "chapter": "FC8 · Self, others, interactions",
        },
    ],
    "biochemistry": [
        {
            "id": "bioc-3",
            "q_zh": "蛋白质一级结构指的是：",
            "q_en": "Primary protein structure refers to:",
            "choices": {
                "A": {"zh": "氨基酸线性序列", "en": "The linear sequence of amino acids"},
                "B": {"zh": "α 螺旋比例 alone", "en": "Alpha-helix content alone"},
                "C": {"zh": "多个亚基组装", "en": "Assembly of multiple subunits"},
                "D": {"zh": "与配体结合的位置 alone", "en": "The binding site alone"},
            },
            "answer": "A",
            "explain_zh": "一级结构是肽链顺序，决定更高层次折叠与功能。",
            "explain_en": "Primary structure is residue order, which constrains higher-order folding and function.",
            "chapter": "1A · Proteins and amino acids",
        },
        {
            "id": "bioc-4",
            "q_zh": "转录发生在细胞的哪个区室（真核生物）？",
            "q_en": "Where does transcription occur in eukaryotes?",
            "choices": {
                "A": {"zh": "细胞核", "en": "Nucleus"},
                "B": {"zh": "线粒体膜间隙 alone", "en": "Mitochondrial intermembrane space alone"},
                "C": {"zh": "高尔基体腔", "en": "Golgi lumen"},
                "D": {"zh": "细胞膜外", "en": "Outside the plasma membrane"},
            },
            "answer": "A",
            "explain_zh": "DNA → mRNA 在核内；成熟 mRNA 出核后在胞质翻译。",
            "explain_en": "DNA is transcribed to mRNA in the nucleus; mature mRNA is translated in the cytoplasm.",
            "chapter": "1B · Gene to protein",
        },
        {
            "id": "bioc-5",
            "q_zh": "点突变若造成错义（missense），意味着：",
            "q_en": "A missense point mutation means:",
            "choices": {
                "A": {"zh": "一个密码子编码不同氨基酸", "en": "One codon codes for a different amino acid"},
                "B": {"zh": "提前出现终止密码子", "en": "A premature stop codon appears"},
                "C": {"zh": "不改变氨基酸序列", "en": "The amino acid sequence is unchanged"},
                "D": {"zh": "删除整条染色体", "en": "An entire chromosome is deleted"},
            },
            "answer": "A",
            "explain_zh": "错义突变改变单个氨基酸；无义突变引入终止；同义突变不改变氨基酸。",
            "explain_en": "Missense swaps one amino acid; nonsense introduces stop; silent leaves the protein sequence unchanged.",
            "chapter": "1C · Heritable information & diversity",
        },
        {
            "id": "bioc-6",
            "q_zh": "糖酵解的净产物（每分子葡萄糖）是：",
            "q_en": "The net products of glycolysis per glucose are:",
            "choices": {
                "A": {"zh": "2 ATP、2 NADH、2 丙酮酸", "en": "2 ATP, 2 NADH, 2 pyruvate"},
                "B": {"zh": "38 ATP、无 NADH", "en": "38 ATP, no NADH"},
                "C": {"zh": "仅 CO₂", "en": "Only CO₂"},
                "D": {"zh": "仅氧气", "en": "Only O₂"},
            },
            "answer": "A",
            "explain_zh": "糖酵解在胞质进行；消耗 2 ATP、产生 4 ATP，净得 2 ATP 与 2 NADH。",
            "explain_en": "Glycolysis occurs in the cytosol; 2 ATP invested and 4 produced → net 2 ATP plus 2 NADH.",
            "chapter": "1D · Bioenergetics and fuel metabolism",
        },
        {
            "id": "bioc-7",
            "q_zh": "竞争性抑制剂对酶动力学的影响通常是：",
            "q_en": "A competitive inhibitor typically:",
            "choices": {
                "A": {"zh": "Km 增大、Vmax 不变", "en": "Increases Km with unchanged Vmax"},
                "B": {"zh": "Vmax 降为零、Km 不变", "en": "Drops Vmax to zero with unchanged Km"},
                "C": {"zh": "Km 与 Vmax 均不变", "en": "Leaves both Km and Vmax unchanged"},
                "D": {"zh": "使酶变性沉淀", "en": "Denatures and precipitates the enzyme"},
            },
            "answer": "A",
            "explain_zh": "竞争抑制剂与底物争活性位点；高底物浓度可克服抑制，Vmax 可达。",
            "explain_en": "Competitive inhibitors bind the active site; high substrate can overcome inhibition, so Vmax is reachable.",
            "chapter": "Chemistry · Biochemistry（CEM）",
        },
    ],
    "bio-biochem": [
        {
            "id": "bb-2",
            "q_zh": "DNA 双螺旋中，碱基配对规则是：",
            "q_en": "In the DNA double helix, base pairing follows:",
            "choices": {
                "A": {"zh": "A–T（2 氢键）、G–C（3 氢键）", "en": "A–T (2 H-bonds), G–C (3 H-bonds)"},
                "B": {"zh": "A–G、T–C", "en": "A–G, T–C"},
                "C": {"zh": "任意碱基随机配对", "en": "Random pairing of any bases"},
                "D": {"zh": "只有 U 参与", "en": "Only U participates"},
            },
            "answer": "A",
            "explain_zh": "Watson–Crick 配对保证互补链复制与转录模板功能。",
            "explain_en": "Watson–Crick pairing enables complementary-strand replication and transcription templates.",
            "chapter": "1C · Heritable information & diversity",
        },
        {
            "id": "bb-3",
            "q_zh": "核糖体在蛋白质合成中的直接作用是：",
            "q_en": "Ribosomes directly:",
            "choices": {
                "A": {"zh": "催化肽键形成（翻译）", "en": "Catalyze peptide-bond formation (translation)"},
                "B": {"zh": "复制 DNA", "en": "Replicate DNA"},
                "C": {"zh": "合成脂肪酸", "en": "Synthesize fatty acids"},
                "D": {"zh": "泵送质子", "en": "Pump protons"},
            },
            "answer": "A",
            "explain_zh": "核糖体读取 mRNA，tRNA 携带氨基酸，rRNA/蛋白组分催化肽键延伸。",
            "explain_en": "Ribosomes read mRNA; tRNAs deliver amino acids; rRNA/protein components catalyze peptide elongation.",
            "chapter": "1B · Gene to protein",
        },
        {
            "id": "bb-4",
            "q_zh": "细胞膜主要由下列哪类分子构成双分子层？",
            "q_en": "The plasma membrane bilayer is mainly built from:",
            "choices": {
                "A": {"zh": "磷脂", "en": "Phospholipids"},
                "B": {"zh": "游离葡萄糖", "en": "Free glucose"},
                "C": {"zh": "核酸双链", "en": "Nucleic acid duplexes"},
                "D": {"zh": "金属离子晶体", "en": "Metallic ion crystals"},
            },
            "answer": "A",
            "explain_zh": "磷脂两亲性形成脂质双层；膜蛋白、胆固醇等镶嵌其中。",
            "explain_en": "Amphipathic phospholipids form the bilayer; proteins and cholesterol are embedded within.",
            "chapter": "2A · Assemblies of molecules, cells, cell groups",
        },
        {
            "id": "bb-5",
            "q_zh": "有氧呼吸最终电子受体是：",
            "q_en": "The terminal electron acceptor in aerobic respiration is:",
            "choices": {
                "A": {"zh": "O₂", "en": "O₂"},
                "B": {"zh": "N₂", "en": "N₂"},
                "C": {"zh": "CO₂", "en": "CO₂"},
                "D": {"zh": "葡萄糖", "en": "Glucose"},
            },
            "answer": "A",
            "explain_zh": "复合体 IV 将电子传给 O₂ 形成 H₂O，完成 ETC。",
            "explain_en": "Complex IV passes electrons to O₂ forming H₂O, completing the ETC.",
            "chapter": "1D · Bioenergetics and fuel metabolism",
        },
        {
            "id": "bb-6",
            "q_zh": "干细胞的关键特征是：",
            "q_en": "A defining feature of stem cells is:",
            "choices": {
                "A": {"zh": "自我更新并具分化潜能", "en": "Self-renewal plus differentiation potential"},
                "B": {"zh": "不能分裂", "en": "Inability to divide"},
                "C": {"zh": "已无细胞核", "en": "Loss of the nucleus"},
                "D": {"zh": "只能产生一种终末细胞", "en": "Production of only one terminal cell type ever"},
            },
            "answer": "A",
            "explain_zh": "干细胞维持未分化池并可在需要时分化；多能/单能程度因类型而异。",
            "explain_en": "Stem cells replenish themselves and can differentiate; potency varies by stem-cell type.",
            "chapter": "2C · Division, differentiation, specialization",
        },
        {
            "id": "bb-7",
            "q_zh": "肾单位中，肾小球的主要功能是：",
            "q_en": "In the nephron, the glomerulus mainly:",
            "choices": {
                "A": {"zh": "滤过血浆形成原尿", "en": "Filters plasma to form filtrate"},
                "B": {"zh": "合成胰岛素", "en": "Synthesizes insulin"},
                "C": {"zh": "产生动作电位传导", "en": "Generates action-potential conduction"},
                "D": {"zh": "分泌胆汁", "en": "Secretes bile"},
            },
            "answer": "A",
            "explain_zh": "肾小球滤过屏障保留血细胞与大蛋白；肾小管重吸收/分泌精细调节尿液。",
            "explain_en": "The glomerular barrier retains cells and large proteins; tubules reabsorb and secrete to refine urine.",
            "chapter": "3B · Main organ systems",
        },
    ],
    "chem-phys": [
        {
            "id": "cp-2",
            "q_zh": "可逆反应达到平衡时：",
            "q_en": "At equilibrium in a reversible reaction:",
            "choices": {
                "A": {"zh": "正逆反应速率相等、宏观组成不变", "en": "Forward and reverse rates are equal; macroscopic composition is steady"},
                "B": {"zh": "反应完全停止", "en": "All reactions stop"},
                "C": {"zh": "只有产物存在", "en": "Only products remain"},
                "D": {"zh": "温度必须为零", "en": "Temperature must be zero"},
            },
            "answer": "A",
            "explain_zh": "平衡是动态平衡：微观反应继续，宏观量不变。",
            "explain_en": "Equilibrium is dynamic: reactions continue microscopically while macroscopic amounts stay constant.",
            "chapter": "5E · Chemical thermodynamics and kinetics",
        },
        {
            "id": "cp-3",
            "q_zh": "强电解质在水溶液中：",
            "q_en": "A strong electrolyte in aqueous solution:",
            "choices": {
                "A": {"zh": "几乎完全电离", "en": "Ionizes almost completely"},
                "B": {"zh": "完全不电离", "en": "Does not ionize at all"},
                "C": {"zh": "只以分子形式存在", "en": "Exists only as neutral molecules"},
                "D": {"zh": "不能导电", "en": "Cannot conduct electricity"},
            },
            "answer": "A",
            "explain_zh": "如 NaCl、强酸强碱几乎全离解；弱电解质仅部分电离。",
            "explain_en": "E.g., NaCl and strong acids/bases dissociate nearly fully; weak electrolytes dissociate partially.",
            "chapter": "5A · Unique nature of water and its solutions",
        },
        {
            "id": "cp-4",
            "q_zh": "串联电路中电流的特点是：",
            "q_en": "In a series circuit, the current:",
            "choices": {
                "A": {"zh": "各元件处相同", "en": "Is the same through each element"},
                "B": {"zh": "各元件处不同且随机", "en": "Differs randomly at each element"},
                "C": {"zh": "恒为零", "en": "Is always zero"},
                "D": {"zh": "只存在于电源内", "en": "Exists only inside the battery"},
            },
            "answer": "A",
            "explain_zh": "串联单一路径，电荷守恒 → 电流处处相等；电压按阻抗分配。",
            "explain_en": "One path in series → charge conservation gives the same current everywhere; voltage divides across elements.",
            "chapter": "4C · Electrochemistry and electrical circuits",
        },
        {
            "id": "cp-5",
            "q_zh": "声波在空气中传播时，介质质点振动方向与波传播方向关系是（纵波）：",
            "q_en": "For sound in air (a longitudinal wave), particle vibration is:",
            "choices": {
                "A": {"zh": "平行于传播方向", "en": "Parallel to the direction of propagation"},
                "B": {"zh": "垂直于传播方向", "en": "Perpendicular to propagation"},
                "C": {"zh": "不存在振动", "en": "There is no vibration"},
                "D": {"zh": "只横向不纵向", "en": "Only transverse, never longitudinal"},
            },
            "answer": "A",
            "explain_zh": "纵波通过压缩/稀疏传播；横波（如绳波）振动垂直于传播方向。",
            "explain_en": "Longitudinal waves travel via compressions and rarefactions; transverse waves vibrate perpendicular to travel.",
            "chapter": "4D · Light and sound interacting with matter",
        },
        {
            "id": "cp-6",
            "q_zh": "凝胶电泳分离 DNA 片段主要依据：",
            "q_en": "Gel electrophoresis separates DNA fragments mainly by:",
            "choices": {
                "A": {"zh": "大小（长度）", "en": "Size (length)"},
                "B": {"zh": "颜色", "en": "Color"},
                "C": {"zh": "样品气味", "en": "Odor"},
                "D": {"zh": "放射性 alone", "en": "Radioactivity alone"},
            },
            "answer": "A",
            "explain_zh": "负电 DNA 向阳极移动；短片段迁移更快。",
            "explain_en": "Negatively charged DNA migrates toward the anode; shorter fragments move faster.",
            "chapter": "5C · Separation and purification methods",
        },
        {
            "id": "cp-7",
            "q_zh": "半衰期是指：",
            "q_en": "Half-life is:",
            "choices": {
                "A": {"zh": "放射性核素活度减半所需时间", "en": "Time for activity of a radionuclide to fall by half"},
                "B": {"zh": "化学反应完成一半所需时间（通用动力学定义）", "en": "Time for any reaction to reach 50% completion (general kinetics)"},
                "C": {"zh": "电子轨道半径", "en": "Electron orbital radius"},
                "D": {"zh": "光速的一半", "en": "Half the speed of light"},
            },
            "answer": "A",
            "explain_zh": "放射性衰变呈指数规律；半衰期为一级衰变特征时间。",
            "explain_en": "Radioactive decay is exponential; half-life is the characteristic time for first-order decay.",
            "chapter": "4E · Atoms, nuclear decay, electronic structure",
        },
    ],
    "psych-soc": [
        {
            "id": "ps-2",
            "q_zh": "差别阈值（just noticeable difference）衡量的是：",
            "q_en": "The just noticeable difference (JND) measures:",
            "choices": {
                "A": {"zh": "可察觉两刺激间最小差异", "en": "The smallest detectable difference between two stimuli"},
                "B": {"zh": "绝对觉察阈限", "en": "The absolute threshold"},
                "C": {"zh": "最大耐受痛阈", "en": "Maximum pain tolerance"},
                "D": {"zh": "记忆保持年限", "en": "Years of memory retention"},
            },
            "answer": "A",
            "explain_zh": "差别阈限关注变化量；绝对阈限关注能否察觉存在。",
            "explain_en": "JND concerns change detection; absolute threshold concerns detecting presence.",
            "chapter": "6A · Sensing the environment",
        },
        {
            "id": "ps-3",
            "q_zh": "自下而上（data-driven）加工主要依赖：",
            "q_en": "Bottom-up (data-driven) processing relies mainly on:",
            "choices": {
                "A": {"zh": "感觉输入本身的特征", "en": "Features of the sensory input itself"},
                "B": {"zh": "先验期望 alone", "en": "Prior expectations alone"},
                "C": {"zh": "完全忽略刺激", "en": "Ignoring the stimulus entirely"},
                "D": {"zh": "只使用长时记忆", "en": "Using only long-term memory"},
            },
            "answer": "A",
            "explain_zh": "自下而上从感觉数据构建知觉；自上而下用情境/期望引导解释。",
            "explain_en": "Bottom-up builds percepts from sensory data; top-down uses context and expectations.",
            "chapter": "6B · Making sense of the environment",
        },
        {
            "id": "ps-4",
            "q_zh": "战斗-逃跑反应主要涉及哪个系统？",
            "q_en": "The fight-or-flight response mainly involves the:",
            "choices": {
                "A": {"zh": "交感神经系统", "en": "Sympathetic nervous system"},
                "B": {"zh": "副交感主导消化 alone", "en": "Parasympathetic digestion alone"},
                "C": {"zh": "视觉皮层 alone", "en": "Visual cortex alone"},
                "D": {"zh": "小脑语言区", "en": "Cerebellar language area"},
            },
            "answer": "A",
            "explain_zh": "交感激活提高心率、呼吸、血糖动员以应对威胁。",
            "explain_en": "Sympathetic activation raises heart rate, breathing, and glucose mobilization for threat response.",
            "chapter": "6C · Responding to the world",
        },
        {
            "id": "ps-5",
            "q_zh": "经典条件反射中，消退（extinction）指：",
            "q_en": "In classical conditioning, extinction is:",
            "choices": {
                "A": {"zh": "反复呈现 CS 而无 UCS 后 CR 减弱", "en": "Weakening of the CR after repeated CS without UCS"},
                "B": {"zh": "永久删除记忆基因", "en": "Permanent deletion of memory genes"},
                "C": {"zh": "强化增加行为", "en": "Reinforcement increasing behavior"},
                "D": {"zh": "只发生在操作条件反射", "en": "Occurring only in operant conditioning"},
            },
            "answer": "A",
            "explain_zh": "消退是学习性抑制，非“抹去”原关联；自发恢复可能发生。",
            "explain_en": "Extinction reflects learned inhibition, not erasure; spontaneous recovery can occur.",
            "chapter": "7A · Individual influences on behavior",
        },
        {
            "id": "ps-6",
            "q_zh": "从众（conformity）最常与下列哪项实验联系？",
            "q_en": "Conformity is most famously linked to:",
            "choices": {
                "A": {"zh": "Asch 线段实验", "en": "Asch’s line-judgment studies"},
                "B": {"zh": "Miller–Urey 实验", "en": "The Miller–Urey experiment"},
                "C": {"zh": "双缝干涉实验", "en": "The double-slit experiment"},
                "D": {"zh": "Krebs 循环", "en": "The Krebs cycle"},
            },
            "answer": "A",
            "explain_zh": "Asch 显示群体压力可使人给出明显错误答案。",
            "explain_en": "Asch showed group pressure can make people give clearly wrong answers.",
            "chapter": "7B · Social processes that influence behavior",
        },
        {
            "id": "ps-7",
            "q_zh": "说服的中心路径（central route）强调：",
            "q_en": "The central route to persuasion emphasizes:",
            "choices": {
                "A": {"zh": "论据质量与深思熟虑", "en": "Argument quality and careful elaboration"},
                "B": {"zh": "名人魅力 alone", "en": "Celebrity attractiveness alone"},
                "C": {"zh": "刺激数量 alone", "en": "Number of stimuli alone"},
                "D": {"zh": "拒绝一切信息", "en": "Rejecting all information"},
            },
            "answer": "A",
            "explain_zh": "中心路径靠逻辑与证据；外周路径靠线索与启发式。",
            "explain_en": "Central route uses logic and evidence; peripheral route uses cues and heuristics.",
            "chapter": "7C · Attitude and behavior change",
        },
        {
            "id": "ps-8",
            "q_zh": "自我服务偏差（self-serving bias）指：",
            "q_en": "The self-serving bias is the tendency to:",
            "choices": {
                "A": {"zh": "把成功归因于自己、失败归因于外因", "en": "Credit success to oneself and failures to external factors"},
                "B": {"zh": "永远责备自己", "en": "Always blame oneself"},
                "C": {"zh": "否认任何自我存在", "en": "Deny any self"},
                "D": {"zh": "只记住他人失败", "en": "Remember only others’ failures"},
            },
            "answer": "A",
            "explain_zh": "该偏差维护自尊与积极自我形象。",
            "explain_en": "This bias protects self-esteem and a positive self-image.",
            "chapter": "8B · Social thinking",
        },
        {
            "id": "ps-9",
            "q_zh": "社会阶层（social stratification）指的是：",
            "q_en": "Social stratification refers to:",
            "choices": {
                "A": {"zh": "社会中不平等、分层的地位与资源分配", "en": "Hierarchical ranking and unequal distribution of status and resources"},
                "B": {"zh": "所有人资源完全均等", "en": "Perfectly equal resources for everyone"},
                "C": {"zh": "仅指地质分层", "en": "Geological rock layers only"},
                "D": {"zh": "神经元分层", "en": "Neuronal lamination only"},
            },
            "answer": "A",
            "explain_zh": "阶层体现阶级、教育、收入等维度的结构性不平等。",
            "explain_en": "Stratification reflects structural inequality across class, education, income, and related dimensions.",
            "chapter": "10A · Social inequality",
        },
    ],
    "cars": [
        {
            "id": "cars-4",
            "q_zh": "遇到“极端/绝对”措辞（always, never, only）的 CARS 选项，通常应：",
            "q_en": "On CARS, options with extreme wording (always, never, only) should usually be:",
            "choices": {
                "A": {"zh": "优先选择", "en": "Chosen first"},
                "B": {"zh": "谨慎怀疑，常与文意不符", "en": "Treated skeptically—they often overstate the passage"},
                "C": {"zh": "忽略题干", "en": "Chosen while ignoring the stem"},
                "D": {"zh": "等于作者立场", "en": "Assumed to equal the author’s view"},
            },
            "answer": "B",
            "explain_zh": "学术论述常有限定；绝对化选项多为过度概括干扰项。",
            "explain_en": "Academic prose is qualified; absolutist options are often overgeneralized distractors.",
            "chapter": "Reasoning Within the Text",
        },
        {
            "id": "cars-5",
            "q_zh": "判断段落功能时，应问：",
            "q_en": "When judging a paragraph’s function, ask:",
            "choices": {
                "A": {"zh": "该段在论证中扮演什么角色（定义、例证、反驳等）", "en": "What role it plays in the argument (define, exemplify, rebut, etc.)"},
                "B": {"zh": "段落最长吗", "en": "Whether it is the longest paragraph"},
                "C": {"zh": "是否包含数字", "en": "Whether it contains numbers"},
                "D": {"zh": "作者国籍", "en": "The author’s nationality"},
            },
            "answer": "A",
            "explain_zh": "结构题考信息功能，而非孤立事实记忆。",
            "explain_en": "Structure questions test informational role, not isolated fact recall.",
            "chapter": "Foundations of Comprehension",
        },
        {
            "id": "cars-6",
            "q_zh": "类比推理题（Beyond the Text）成立需满足：",
            "q_en": "An analogy item (Beyond the Text) works only if:",
            "choices": {
                "A": {"zh": "对应关系与文中原则一致", "en": "The correspondence matches the passage principle"},
                "B": {"zh": "新情境越陌生越好", "en": "The new scenario is as unfamiliar as possible"},
                "C": {"zh": "可违背作者前提", "en": "It may violate the author’s premises"},
                "D": {"zh": "只需字面相似", "en": "Surface wording similarity is enough"},
            },
            "answer": "A",
            "explain_zh": "类推须保持逻辑关系一致，而非表面相似。",
            "explain_en": "Valid analogies preserve the logical relation, not mere surface similarity.",
            "chapter": "Reasoning Beyond the Text",
        },
        {
            "id": "cars-7",
            "q_zh": "作者“语气”题应依据：",
            "q_en": "Tone questions should be answered using:",
            "choices": {
                "A": {"zh": "文中措辞与修辞的整体倾向", "en": "Overall diction and rhetorical stance in the text"},
                "B": {"zh": "你对话题的个人喜好", "en": "Your personal opinion of the topic"},
                "C": {"zh": "选项最短者", "en": "The shortest option"},
                "D": {"zh": "文章发表年份 alone", "en": "Publication year alone"},
            },
            "answer": "A",
            "explain_zh": "语气来自用词（谨慎、批判、赞赏等），须文内有据。",
            "explain_en": "Tone comes from word choice (cautious, critical, approving, etc.) and must be text-supported.",
            "chapter": "Foundations of Comprehension",
        },
    ],
    "verbal": [
        {
            "id": "verb-3",
            "q_zh": "SURGEON : SCALPEL :: WRITER : ?",
            "q_en": "SURGEON : SCALPEL :: WRITER : ?",
            "choices": {
                "A": {"zh": "Pen（笔）", "en": "Pen"},
                "B": {"zh": "Hospital（医院）", "en": "Hospital"},
                "C": {"zh": "Patient（病人）", "en": "Patient"},
                "D": {"zh": "Medicine（药物）", "en": "Medicine"},
            },
            "answer": "A",
            "explain_zh": "职业与其常用工具；手术刀之于外科医生，如同笔之于作家。",
            "explain_en": "Profession to characteristic tool—a scalpel for a surgeon, a pen for a writer.",
            "chapter": "Analogies（词义类比）",
        },
        {
            "id": "verb-4",
            "q_zh": "HOT : COLD :: GENEROUS : ?",
            "q_en": "HOT : COLD :: GENEROUS : ?",
            "choices": {
                "A": {"zh": "Stingy（吝啬的）", "en": "Stingy"},
                "B": {"zh": "Wealthy（富有的）", "en": "Wealthy"},
                "C": {"zh": "Happy（快乐的）", "en": "Happy"},
                "D": {"zh": "Tall（高的）", "en": "Tall"},
            },
            "answer": "A",
            "explain_zh": "反义关系：热/冷，慷慨/吝啬。",
            "explain_en": "Antonym relation: hot/cold, generous/stingy.",
            "chapter": "Analogies（词义类比）",
        },
        {
            "id": "verb-5",
            "q_zh": "推断题（reading）与细节题的关键区别是：",
            "q_en": "Inference items differ from detail items because inferences:",
            "choices": {
                "A": {"zh": "需合理推出但未逐字写明", "en": "Must be reasonably drawn though not stated verbatim"},
                "B": {"zh": "可完全脱离文本", "en": "May ignore the text entirely"},
                "C": {"zh": "必须逐字复制原文", "en": "Must copy the passage word for word"},
                "D": {"zh": "只考词义", "en": "Test only vocabulary"},
            },
            "answer": "A",
            "explain_zh": "推断须有文本证据链，但不能要求文中原句。",
            "explain_en": "Inferences need a textual evidence chain but need not be verbatim quotes.",
            "chapter": "Reading Comprehension（阅读理解）",
        },
        {
            "id": "verb-6",
            "q_zh": "TREE : FOREST :: STAR : ?",
            "q_en": "TREE : FOREST :: STAR : ?",
            "choices": {
                "A": {"zh": "Galaxy（星系）", "en": "Galaxy"},
                "B": {"zh": "Planet（行星）", "en": "Planet"},
                "C": {"zh": "Moon（月亮）", "en": "Moon"},
                "D": {"zh": "Telescope（望远镜）", "en": "Telescope"},
            },
            "answer": "A",
            "explain_zh": "部分-整体：树组成森林，恒星（大量）组成星系。",
            "explain_en": "Part-to-whole: trees make a forest; stars (collectively) make a galaxy.",
            "chapter": "Analogies（词义类比）",
        },
    ],
    "inductive-reasoning": [
        {
            "id": "ind-2",
            "q_zh": "图形归类题第一步通常是：",
            "q_en": "On figure-grouping items, the first step is usually to:",
            "choices": {
                "A": {"zh": "找出多数图形共享的属性", "en": "Find the attribute shared by most figures"},
                "B": {"zh": "随机选一组", "en": "Pick a group at random"},
                "C": {"zh": "只数顶点忽略形状", "en": "Count vertices only, ignore shape"},
                "D": {"zh": "假设无规则", "en": "Assume there is no rule"},
            },
            "answer": "A",
            "explain_zh": "归类考共同特征；例外项即答案或需排除项。",
            "explain_en": "Grouping tests shared features; the odd figure is often the key.",
            "chapter": "Figure Grouping（图形归类）",
        },
        {
            "id": "ind-3",
            "q_zh": "数字序列 2, 6, 18, 54, … 下一项最可能是：",
            "q_en": "In the number series 2, 6, 18, 54, … the next term is most likely:",
            "choices": {
                "A": {"zh": "162", "en": "162"},
                "B": {"zh": "108", "en": "108"},
                "C": {"zh": "72", "en": "72"},
                "D": {"zh": "60", "en": "60"},
            },
            "answer": "A",
            "explain_zh": "公比为 3 的等比数列：54 × 3 = 162。",
            "explain_en": "Geometric sequence with ratio 3: 54 × 3 = 162.",
            "chapter": "Number and Letter Series（数字与字母序列）",
        },
        {
            "id": "ind-4",
            "q_zh": "图形序列中“每隔一项”规则意味着：",
            "q_en": "An “every other term” rule in a figure series means:",
            "choices": {
                "A": {"zh": "奇偶项可能遵循不同子规则", "en": "Odd and even positions may follow different sub-rules"},
                "B": {"zh": "序列只有两项", "en": "The series has only two terms"},
                "C": {"zh": "必须忽略旋转", "en": "Rotation must be ignored"},
                "D": {"zh": "答案恒为 A", "en": "The answer is always A"},
            },
            "answer": "A",
            "explain_zh": "交替规则常见：如奇项旋转、偶项加元素。",
            "explain_en": "Alternating rules are common—e.g., odd terms rotate, even terms add elements.",
            "chapter": "Figure Series（图形序列）",
        },
    ],
    "quantitative": [
        {
            "id": "quant-2",
            "q_zh": "算式 15% of 80 等于：",
            "q_en": "15% of 80 equals:",
            "choices": {
                "A": {"zh": "12", "en": "12"},
                "B": {"zh": "8", "en": "8"},
                "C": {"zh": "15", "en": "15"},
                "D": {"zh": "120", "en": "120"},
            },
            "answer": "A",
            "explain_zh": "0.15 × 80 = 12。",
            "explain_en": "0.15 × 80 = 12.",
            "chapter": "Fundamental Operations（基本运算）",
        },
        {
            "id": "quant-3",
            "q_zh": "火车以 60 km/h 行驶 2.5 小时，路程为：",
            "q_en": "A train at 60 km/h for 2.5 hours travels:",
            "choices": {
                "A": {"zh": "150 km", "en": "150 km"},
                "B": {"zh": "120 km", "en": "120 km"},
                "C": {"zh": "62.5 km", "en": "62.5 km"},
                "D": {"zh": "240 km", "en": "240 km"},
            },
            "answer": "A",
            "explain_zh": "路程 = 速度 × 时间 = 60 × 2.5 = 150 km。",
            "explain_en": "Distance = rate × time = 60 × 2.5 = 150 km.",
            "chapter": "Problem Solving（应用题）",
        },
        {
            "id": "quant-4",
            "q_zh": "条形图显示三年销量上升，最稳妥结论是：",
            "q_en": "If a bar chart shows rising sales over three years, the safest conclusion is:",
            "choices": {
                "A": {"zh": "这三年销量呈上升趋势（在图表范围内）", "en": "Sales trend upward over those three years (within the chart’s scope)"},
                "B": {"zh": "未来永远上升", "en": "Sales will rise forever"},
                "C": {"zh": "利润必然翻倍", "en": "Profit must have doubled"},
                "D": {"zh": "样本代表全球", "en": "The sample represents the whole world"},
            },
            "answer": "A",
            "explain_zh": "资料题结论不能超出图表时间与变量；避免过度外推。",
            "explain_en": "Data items cannot exceed the chart’s time frame and variables—avoid over-extrapolation.",
            "chapter": "Data Interpretation（资料判读）",
        },
    ],
    "perceptual-acuity": [
        {
            "id": "perc-2",
            "q_zh": "隐藏图形题的有效策略是：",
            "q_en": "A useful strategy on hidden-figure items is to:",
            "choices": {
                "A": {"zh": "锁定目标外形轮廓，在复杂背景中逐段匹配", "en": "Lock onto the target outline and match segments in the clutter"},
                "B": {"zh": "只看图形中心", "en": "Look only at the figure’s center"},
                "C": {"zh": "忽略线条方向", "en": "Ignore line orientation"},
                "D": {"zh": "闭一只眼一定更快", "en": "Closing one eye is always faster"},
            },
            "answer": "A",
            "explain_zh": "局部轮廓匹配比整体扫视更抗干扰。",
            "explain_en": "Piecewise outline matching beats unfocused whole-figure scanning.",
            "chapter": "Hidden Figure（隐藏图形）",
        },
        {
            "id": "perc-3",
            "q_zh": "判断两列信息是否“完全相同”时，应：",
            "q_en": "To decide whether two columns show identical information, you should:",
            "choices": {
                "A": {"zh": "逐字符比对，注意易混字符（如 0/O）", "en": "Compare character by character, watching confusable glyphs (0/O)"},
                "B": {"zh": "只看首尾字符", "en": "Check only first and last characters"},
                "C": {"zh": "假设总相同", "en": "Assume they are always identical"},
                "D": {"zh": "忽略标点", "en": "Ignore all punctuation"},
            },
            "answer": "A",
            "explain_zh": "细微差异常藏在中间字符、标点或大小写。",
            "explain_en": "Subtle differences often hide in middle characters, punctuation, or case.",
            "chapter": "Identical Information（相同信息）",
        },
        {
            "id": "perc-4",
            "q_zh": "水平镜像与垂直镜像的区别是：",
            "q_en": "A horizontal mirror flip differs from a vertical flip because:",
            "choices": {
                "A": {"zh": "前者左右互换，后者上下互换", "en": "Horizontal swaps left–right; vertical swaps top–bottom"},
                "B": {"zh": "二者完全相同", "en": "They are identical"},
                "C": {"zh": "镜像等于平移", "en": "Mirroring equals translation"},
                "D": {"zh": "只有颜色改变", "en": "Only color changes"},
            },
            "answer": "A",
            "explain_zh": "镜像轴方向决定翻转维度；均不同于旋转。",
            "explain_en": "Mirror-axis orientation sets which axis flips; neither is the same as rotation.",
            "chapter": "Mirror Image（镜像）",
        },
    ],
}


def merge_practice(base: dict) -> dict:
    """Deep-merge practice banks by slug, skipping duplicate ids."""
    merged = copy.deepcopy(base)
    for slug, extra_items in EXTRA_PRACTICE.items():
        if slug not in merged:
            merged[slug] = []
        seen = {item.get("id") for item in merged[slug] if item.get("id")}
        for item in extra_items:
            item_id = item.get("id")
            if item_id and item_id in seen:
                continue
            merged[slug].append(copy.deepcopy(item))
            if item_id:
                seen.add(item_id)
    return merged
