"""Textbook companion data: glossary, formulas, exam tips, and study paths.

Consumed by study/materials views; kept separate from notes.py for maintainability.
"""

from __future__ import annotations

GLOSSARY: list[dict[str, str | list[str]]] = [
    {"term": "Km", "term_zh": "米氏常数", "def_zh": "酶促反应速率为最大速率一半时的底物浓度；反映酶与底物亲和力。", "def_en": "Substrate concentration at half-maximal reaction rate; reflects enzyme–substrate affinity.", "subjects": ["biochemistry", "biology", "bio-biochem"]},
    {"term": "Vmax", "term_zh": "最大反应速率", "def_zh": "酶饱和底物时单位时间产物生成量；受酶浓度影响。", "def_en": "Product formed per time when enzyme is substrate-saturated; scales with enzyme concentration.", "subjects": ["biochemistry", "bio-biochem"]},
    {"term": "ATP", "term_zh": "三磷酸腺苷", "def_zh": "细胞主要能量货币；水解释放能量驱动吸能反应。", "def_en": "Primary cellular energy currency; hydrolysis drives endergonic processes.", "subjects": ["biochemistry", "biology", "bio-biochem"]},
    {"term": "DNA", "term_zh": "脱氧核糖核酸", "def_zh": "双链核酸储存遗传信息；由核苷酸聚合而成。", "def_en": "Double-stranded nucleic acid storing genetic information as nucleotide polymers.", "subjects": ["biology", "biochemistry", "bio-biochem"]},
    {"term": "RNA", "term_zh": "核糖核酸", "def_zh": "单链核酸；参与转录、翻译与调控。", "def_en": "Single-stranded nucleic acid in transcription, translation, and regulation.", "subjects": ["biology", "biochemistry", "bio-biochem"]},
    {"term": "Central dogma", "term_zh": "中心法则", "def_zh": "遗传信息从 DNA 流向 RNA 再流向蛋白质。", "def_en": "Genetic information flows DNA → RNA → protein.", "subjects": ["biology", "biochemistry", "bio-biochem"]},
    {"term": "Homeostasis", "term_zh": "稳态", "def_zh": "内环境参数在反馈调节下维持相对稳定。", "def_en": "Internal parameters kept relatively stable via feedback regulation.", "subjects": ["biology", "bio-biochem"]},
    {"term": "Osmosis", "term_zh": "渗透", "def_zh": "水分子经半透膜从低溶质浓度侧向高浓度侧扩散。", "def_en": "Water diffuses across a semipermeable membrane toward higher solute concentration.", "subjects": ["biology", "chemistry", "physics"]},
    {"term": "Mitosis", "term_zh": "有丝分裂", "def_zh": "体细胞分裂产生遗传相同的子细胞。", "def_en": "Somatic cell division producing genetically identical daughter cells.", "subjects": ["biology", "bio-biochem"]},
    {"term": "Meiosis", "term_zh": "减数分裂", "def_zh": "产生单倍体配子；包含重组增加遗传多样性。", "def_en": "Produces haploid gametes with recombination increasing diversity.", "subjects": ["biology", "bio-biochem"]},
    {"term": "Allele", "term_zh": "等位基因", "def_zh": "同一基因座的不同版本。", "def_en": "Alternative versions of a gene at a locus.", "subjects": ["biology", "bio-biochem"]},
    {"term": "pH", "term_zh": "酸碱度", "def_zh": "溶液氢离子活度的负对数；酸性 <7，碱性 >7。", "def_en": "Negative log of hydrogen-ion activity; acidic <7, basic >7.", "subjects": ["chemistry", "chem-phys", "biochemistry"]},
    {"term": "pKa", "term_zh": "酸解离常数负对数", "def_zh": "酸一半电离时的 pH；衡量酸强度。", "def_en": "pH at which half the acid is deprotonated; measures acid strength.", "subjects": ["chemistry", "chem-phys", "biochemistry"]},
    {"term": "Buffer", "term_zh": "缓冲溶液", "def_zh": "弱酸及其共轭碱（或反之）抵抗 pH 变化。", "def_en": "Weak acid/conjugate base pair resists pH change upon acid/base addition.", "subjects": ["chemistry", "chem-phys", "biochemistry"]},
    {"term": "Oxidation", "term_zh": "氧化", "def_zh": "失去电子或氧化数升高。", "def_en": "Loss of electrons or increase in oxidation number.", "subjects": ["chemistry", "chem-phys"]},
    {"term": "Reduction", "term_zh": "还原", "def_zh": "获得电子或氧化数降低。", "def_en": "Gain of electrons or decrease in oxidation number.", "subjects": ["chemistry", "chem-phys"]},
    {"term": "Equilibrium constant", "term_zh": "平衡常数 K", "def_zh": "反应达平衡时产物与反应物浓度比（按化学计量）。", "def_en": "Ratio of product to reactant concentrations at equilibrium (stoichiometric).", "subjects": ["chemistry", "chem-phys"]},
    {"term": "Enthalpy", "term_zh": "焓 ΔH", "def_zh": "系统热含量变化；放热 ΔH<0，吸热 ΔH>0。", "def_en": "Heat content change; exothermic ΔH<0, endothermic ΔH>0.", "subjects": ["chemistry", "physics", "chem-phys"]},
    {"term": "Entropy", "term_zh": "熵 ΔS", "def_zh": "系统无序度度量；自发过程常伴随总熵增。", "def_en": "Measure of disorder; spontaneous processes often increase total entropy.", "subjects": ["chemistry", "physics", "chem-phys"]},
    {"term": "Gibbs free energy", "term_zh": "吉布斯自由能 ΔG", "def_zh": "ΔG = ΔH − TΔS；ΔG<0 反应在恒定 T、P 下自发。", "def_en": "ΔG = ΔH − TΔS; ΔG<0 means spontaneous at constant T and P.", "subjects": ["chemistry", "biochemistry", "chem-phys"]},
    {"term": "Activation energy", "term_zh": "活化能 Ea", "def_zh": "反应物到达过渡态所需额外能量；决定速率。", "def_en": "Extra energy to reach transition state; governs reaction rate.", "subjects": ["chemistry", "chem-phys", "biochemistry"]},
    {"term": "Nucleophile", "term_zh": "亲核试剂", "def_zh": "富电子物种进攻缺电子中心。", "def_en": "Electron-rich species attacking electron-deficient centers.", "subjects": ["chemistry", "chem-phys"]},
    {"term": "Electrophile", "term_zh": "亲电试剂", "def_zh": "缺电子物种接受电子对。", "def_en": "Electron-deficient species accepting electron pairs.", "subjects": ["chemistry", "chem-phys"]},
    {"term": "Stereoisomer", "term_zh": "立体异构体", "def_zh": "连接相同但空间排列不同的异构体。", "def_en": "Isomers with identical connectivity but different spatial arrangement.", "subjects": ["chemistry", "chem-phys"]},
    {"term": "Peptide bond", "term_zh": "肽键", "def_zh": "氨基酸羧基与氨基脱水缩合形成的酰胺键。", "def_en": "Amide linkage from condensation of amino acid carboxyl and amino groups.", "subjects": ["biochemistry", "bio-biochem", "chemistry"]},
    {"term": "Isoelectric point", "term_zh": "等电点 pI", "def_zh": "分子净电荷为零的 pH。", "def_en": "pH where a molecule has zero net charge.", "subjects": ["biochemistry", "bio-biochem"]},
    {"term": "Glycolysis", "term_zh": "糖酵解", "def_zh": "胞质中将葡萄糖分解为丙酮酸并产少量 ATP。", "def_en": "Cytoplasmic pathway splitting glucose to pyruvate with modest ATP yield.", "subjects": ["biochemistry", "bio-biochem", "biology"]},
    {"term": "TCA cycle", "term_zh": "三羧酸循环", "def_zh": "线粒体氧化乙酰 CoA 产 NADH/FADH₂ 与 GTP。", "def_en": "Mitochondrial oxidation of acetyl-CoA yielding NADH/FADH₂ and GTP.", "subjects": ["biochemistry", "bio-biochem"]},
    {"term": "Oxidative phosphorylation", "term_zh": "氧化磷酸化", "def_zh": "ETC 电子传递驱动质子梯度合成 ATP。", "def_en": "ETC electron transfer drives proton gradient for ATP synthesis.", "subjects": ["biochemistry", "bio-biochem", "biology"]},
    {"term": "Newton's second law", "term_zh": "牛顿第二定律", "def_zh": "物体加速度与合外力成正比、与质量成反比 ΣF=ma。", "def_en": "Acceleration proportional to net force and inversely to mass: ΣF=ma.", "subjects": ["physics", "chem-phys"]},
    {"term": "Work", "term_zh": "功", "def_zh": "力在位移方向上的分量与位移的乘积 W=F·d。", "def_en": "Force component along displacement times distance: W=F·d.", "subjects": ["physics", "chem-phys"]},
    {"term": "Power", "term_zh": "功率", "def_zh": "单位时间所做的功或能量转移速率 P=W/t。", "def_en": "Rate of work or energy transfer per time: P=W/t.", "subjects": ["physics", "chem-phys"]},
    {"term": "Momentum", "term_zh": "动量", "def_zh": "质量与速度的乘积 p=mv；孤立系统动量守恒。", "def_en": "Mass times velocity p=mv; conserved in isolated systems.", "subjects": ["physics", "chem-phys"]},
    {"term": "Bernoulli principle", "term_zh": "伯努利原理", "def_zh": "理想流体沿流线：速度增则静压降。", "def_en": "Along a streamline in ideal flow: higher speed lowers static pressure.", "subjects": ["physics", "chem-phys"]},
    {"term": "Poiseuille's law", "term_zh": "泊肃叶定律", "def_zh": "层流管状流体流量与半径四次方成正比。", "def_en": "Laminar tube flow proportional to radius to the fourth power.", "subjects": ["physics", "chem-phys"]},
    {"term": "Ohm's law", "term_zh": "欧姆定律", "def_zh": "电压等于电流与电阻之积 V=IR。", "def_en": "Voltage equals current times resistance: V=IR.", "subjects": ["physics", "chem-phys"]},
    {"term": "Capacitance", "term_zh": "电容", "def_zh": "储存电荷能力 C=Q/V；平行板电容与面积/间距相关。", "def_en": "Charge storage ability C=Q/V; parallel plates depend on area and separation.", "subjects": ["physics", "chem-phys"]},
    {"term": "Snell's law", "term_zh": "斯涅尔定律", "def_zh": "折射时 n₁sinθ₁ = n₂sinθ₂。", "def_en": "Refraction relation n₁sinθ₁ = n₂sinθ₂.", "subjects": ["physics", "chem-phys"]},
    {"term": "Doppler effect", "term_zh": "多普勒效应", "def_zh": "波源或观察者运动改变观测频率。", "def_en": "Relative motion of source/observer shifts observed frequency.", "subjects": ["physics", "chem-phys"]},
    {"term": "Photoelectric effect", "term_zh": "光电效应", "def_zh": "光电子动能取决于频率而非光强；需阈值频率。", "def_en": "Photoelectron KE depends on frequency, not intensity; threshold frequency required.", "subjects": ["physics", "chem-phys"]},
    {"term": "Half-life", "term_zh": "半衰期", "def_zh": "放射性或反应物浓度降至一半所需时间。", "def_en": "Time for radioactivity or reactant concentration to halve.", "subjects": ["physics", "chemistry", "chem-phys"]},
    {"term": "Classical conditioning", "term_zh": "经典条件反射", "def_zh": "中性刺激与无条件刺激配对后诱发反应。", "def_en": "Neutral stimulus paired with unconditioned stimulus elicits conditioned response.", "subjects": ["behavioral-social", "psych-soc"]},
    {"term": "Operant conditioning", "term_zh": "操作条件反射", "def_zh": "行为后果（强化/惩罚）塑造未来行为。", "def_en": "Behavior consequences (reinforcement/punishment) shape future actions.", "subjects": ["behavioral-social", "psych-soc"]},
    {"term": "Cognitive dissonance", "term_zh": "认知失调", "def_zh": "态度与行为或信念不一致引发心理不适。", "def_en": "Psychological discomfort when attitudes, behaviors, or beliefs conflict.", "subjects": ["behavioral-social", "psych-soc"]},
    {"term": "Social facilitation", "term_zh": "社会促进", "def_zh": "他人在场提高简单或熟练任务表现。", "def_en": "Others’ presence improves performance on simple or well-learned tasks.", "subjects": ["behavioral-social", "psych-soc"]},
    {"term": "Stereotype threat", "term_zh": "刻板印象威胁", "def_zh": "担心证实负面刻板印象损害任务表现。", "def_en": "Fear of confirming negative stereotypes impairs performance.", "subjects": ["behavioral-social", "psych-soc"]},
    {"term": "SES", "term_zh": "社会经济地位", "def_zh": "收入、教育、职业等综合社会地位指标。", "def_en": "Composite social standing from income, education, and occupation.", "subjects": ["behavioral-social", "psych-soc"]},
    {"term": "Social capital", "term_zh": "社会资本", "def_zh": "社会关系网络带来的资源与机会。", "def_en": "Resources and opportunities from social networks and relationships.", "subjects": ["behavioral-social", "psych-soc"]},
    {"term": "Signal detection", "term_zh": "信号检测", "def_zh": "区分真实信号与噪声；击中率与虚报率权衡。", "def_en": "Discriminating signal from noise; trade hits vs false alarms.", "subjects": ["psych-soc", "behavioral-social"]},
    {"term": "Thesis", "term_zh": "主旨论点", "def_zh": "作者试图证明或传达的核心主张；区别于话题。", "def_en": "Author’s central claim to establish; distinct from topic.", "subjects": ["cars", "verbal"]},
    {"term": "Inference", "term_zh": "推断", "def_zh": "基于文本证据的合理结论，非凭空猜测。", "def_en": "Reasonable conclusion grounded in textual evidence, not guesswork.", "subjects": ["cars", "verbal"]},
    {"term": "Analogy relation", "term_zh": "类比关系", "def_zh": "词对之间的逻辑关系（同义、反义、因果等）。", "def_en": "Logical relation between word pairs (synonym, antonym, cause-effect, etc.).", "subjects": ["verbal"]},
    {"term": "Proportion", "term_zh": "比例", "def_zh": "两比值相等的关系 a/b = c/d。", "def_en": "Equality of two ratios: a/b = c/d.", "subjects": ["quantitative"]},
    {"term": "Mean", "term_zh": "平均数", "def_zh": "数值总和除以个数；受极端值影响。", "def_en": "Sum divided by count; sensitive to outliers.", "subjects": ["quantitative"]},
    {"term": "Median", "term_zh": "中位数", "def_zh": "排序后中间值；对极端值更稳健。", "def_en": "Middle value when ordered; robust to outliers.", "subjects": ["quantitative"]},
    {"term": "Antigen", "term_zh": "抗原", "def_zh": "引发免疫识别的外来分子表位。", "def_en": "Foreign molecular epitope triggering immune recognition.", "subjects": ["biology", "bio-biochem"]},
    {"term": "Antibody", "term_zh": "抗体", "def_zh": "B 细胞分泌的免疫球蛋白，特异性结合抗原。", "def_en": "Immunoglobulin from B cells binding specific antigens.", "subjects": ["biology", "bio-biochem"]},
    {"term": "Action potential", "term_zh": "动作电位", "def_zh": "膜去极化触发的全或无电信号脉冲。", "def_en": "All-or-none electrical spike from membrane depolarization.", "subjects": ["biology", "bio-biochem", "psych-soc"]},
    {"term": "Synapse", "term_zh": "突触", "def_zh": "神经元间或神经元–效应器间的信号传递界面。", "def_en": "Junction for signaling between neurons or neuron and effector.", "subjects": ["biology", "bio-biochem", "psych-soc"]},
    {"term": "Operon", "term_zh": "操纵子", "def_zh": "原核中受共同调控的一组相邻基因。", "def_en": "Cluster of adjacent prokaryotic genes under shared regulation.", "subjects": ["biology", "bio-biochem"]},
    {"term": "Hardy-Weinberg equilibrium", "term_zh": "哈迪–温伯格平衡", "def_zh": "理想条件下等位基因频率代际不变的模型。", "def_en": "Model where allele frequencies stay constant across generations under ideal conditions.", "subjects": ["biology", "bio-biochem"]},
    {"term": "Colligative property", "term_zh": "依数性", "def_zh": "取决于溶质粒子数而非种类的性质（沸点升等）。", "def_en": "Property depending on solute particle count, not chemical identity.", "subjects": ["chemistry", "chem-phys"]},
    {"term": "Michaelis-Menten kinetics", "term_zh": "米氏动力学", "def_zh": "酶促速率 v = Vmax[S]/(Km + [S])。", "def_en": "Enzyme rate law v = Vmax[S]/(Km + [S]).", "subjects": ["biochemistry", "bio-biochem", "chem-phys"]},
    {"term": "Foundational Concept", "term_zh": "基础概念（FC）", "def_zh": "AAMC MCAT 大纲按 FC 组织科学内容。", "def_en": "AAMC MCAT content organized by Foundational Concepts.", "subjects": ["bio-biochem", "chem-phys", "psych-soc"]},
    {"term": "CARS", "term_zh": "批判分析与推理", "def_zh": "MCAT 篇章阅读科；考理解、文内与文外推理。", "def_en": "MCAT passage section testing comprehension and within/beyond-text reasoning.", "subjects": ["cars"]},
]

FORMULAS: dict[str, list[dict[str, str]]] = {
    "biology": [
        {"title_zh": "哈迪–温伯格", "title_en": "Hardy–Weinberg", "formula": "p² + 2pq + q² = 1", "note_zh": "p、q 为等位基因频率；理想种群假设。", "note_en": "p and q are allele frequencies under ideal-population assumptions."},
        {"title_zh": "种群增长（指数）", "title_en": "Exponential population growth", "formula": "N(t) = N₀e^(rt)", "note_zh": "r 为增长率；资源无限假设。", "note_en": "r is growth rate; assumes unlimited resources."},
        {"title_zh": "种群增长（逻辑）", "title_en": "Logistic growth", "formula": "dN/dt = rN(1 − N/K)", "note_zh": "K 为环境容纳量。", "note_en": "K is carrying capacity."},
        {"title_zh": "心输出量", "title_en": "Cardiac output", "formula": "CO = HR × SV", "note_zh": "心率 × 每搏输出量。", "note_en": "Heart rate times stroke volume."},
        {"title_zh": "血压–流量–阻力", "title_en": "Pressure–flow–resistance", "formula": "ΔP = Q × R", "note_zh": "类比欧姆定律的循环生理。", "note_en": "Circulatory analogy to Ohm’s law."},
        {"title_zh": "呼吸交换比", "title_en": "Respiratory exchange ratio", "formula": "RER = VCO₂/VO₂", "note_zh": "反映代谢底物（糖 vs 脂肪）。", "note_en": "Reflects metabolic substrate (carbohydrate vs fat)."},
        {"title_zh": "膜电位（静息近似）", "title_en": "Resting membrane potential (approx.)", "formula": "E ≈ −60 to −70 mV", "note_zh": "因细胞而异；K⁺通透性主导。", "note_en": "Cell-specific; dominated by K⁺ permeability."},
        {"title_zh": "遗传距离（重组率）", "title_en": "Genetic distance (recombination)", "formula": "RF = recombinants / total offspring", "note_zh": "重组率与基因距离相关。", "note_en": "Recombination frequency maps to gene distance."},
        {"title_zh": "稀释公式", "title_en": "Dilution", "formula": "C₁V₁ = C₂V₂", "note_zh": "溶液稀释前后溶质摩尔数守恒。", "note_en": "Moles of solute conserved before/after dilution."},
        {"title_zh": "渗透压（范特尔）", "title_en": "Osmotic pressure (van’t Hoff)", "formula": "π = iMRT", "note_zh": "i 为粒子数因子；胶体渗透压生理重要。", "note_en": "i is ionization factor; colloid osmotic pressure matters physiologically."},
        {"title_zh": "光合量子产额", "title_en": "Photosynthetic quantum yield", "formula": "O₂ evolved per photon absorbed", "note_zh": "光反应效率概念题常见。", "note_en": "Common concept item on light-reaction efficiency."},
        {"title_zh": "能量传递效率", "title_en": "Trophic energy transfer", "formula": "~10% to next level", "note_zh": "营养级间能量大量以热散失。", "note_en": "Most energy lost as heat between trophic levels."},
    ],
    "chemistry": [
        {"title_zh": "理想气体", "title_en": "Ideal gas law", "formula": "PV = nRT", "note_zh": "注意 R 与 P、V 单位匹配。", "note_en": "Match R units to pressure and volume."},
        {"title_zh": "吉布斯自由能", "title_en": "Gibbs free energy", "formula": "ΔG = ΔH − TΔS", "note_zh": "ΔG<0 自发（恒 T、P）。", "note_en": "ΔG<0 spontaneous at constant T and P."},
        {"title_zh": "平衡常数与 ΔG", "title_en": "ΔG and K", "formula": "ΔG° = −RT ln K", "note_zh": "标准态下联系能量与平衡位置。", "note_en": "Links energy to equilibrium position at standard state."},
        {"title_zh": "Henderson–Hasselbalch", "title_en": "Henderson–Hasselbalch", "formula": "pH = pKa + log([A⁻]/[HA])", "note_zh": "缓冲溶液 pH 估算。", "note_en": "Estimate buffer pH."},
        {"title_zh": "反应速率", "title_en": "Rate law", "formula": "rate = k[A]^m[B]^n", "note_zh": "级数由实验确定。", "note_en": "Orders determined experimentally."},
        {"title_zh": "阿伦尼乌斯", "title_en": "Arrhenius equation", "formula": "k = Ae^(−Ea/RT)", "note_zh": "Ea 为活化能。", "note_en": "Ea is activation energy."},
        {"title_zh": "摩尔浓度", "title_en": "Molarity", "formula": "M = n / V (L)", "note_zh": "溶质摩尔数除以溶液体积。", "note_en": "Moles of solute per liter of solution."},
        {"title_zh": "限量反应物产率", "title_en": "Percent yield", "formula": "yield% = (actual/theoretical) × 100%", "note_zh": "理论产率由化学计量计算。", "note_en": "Theoretical yield from stoichiometry."},
        {"title_zh": "Beer 定律", "title_en": "Beer’s law", "formula": "A = εlc", "note_zh": "吸光度与浓度线性（稀溶液）。", "note_en": "Absorbance linear with concentration (dilute)."},
        {"title_zh": "能斯特方程", "title_en": "Nernst equation", "formula": "E = E° − (RT/nF) ln Q", "note_zh": "非标准态电池电压。", "note_en": "Cell voltage under nonstandard conditions."},
        {"title_zh": "沸点升高", "title_en": "Boiling-point elevation", "formula": "ΔTb = iKbm", "note_zh": "依数性；m 为质量摩尔浓度。", "note_en": "Colligative; m is molality."},
        {"title_zh": "凝固点降低", "title_en": "Freezing-point depression", "formula": "ΔTf = iKfm", "note_zh": "溶质降低凝固点。", "note_en": "Solute lowers freezing point."},
        {"title_zh": "pH 定义", "title_en": "pH definition", "formula": "pH = −log[H⁺]", "note_zh": "氢离子活度的负对数。", "note_en": "Negative log of hydrogen-ion activity."},
        {"title_zh": "氧化数变化", "title_en": "Redox electron transfer", "formula": "n = Δoxidation number × atoms", "note_zh": "配平半反应求电子数。", "note_en": "Balance half-reactions to find electrons."},
    ],
    "physics": [
        {"title_zh": "牛顿第二定律", "title_en": "Newton’s second law", "formula": "F = ma", "note_zh": "矢量方程；用分量求解。", "note_en": "Vector equation; solve in components."},
        {"title_zh": "动能", "title_en": "Kinetic energy", "formula": "KE = ½mv²", "note_zh": "与速度平方成正比。", "note_en": "Proportional to velocity squared."},
        {"title_zh": "重力势能", "title_en": "Gravitational PE", "formula": "PE = mgh", "note_zh": "近地表近似。", "note_en": "Near-surface approximation."},
        {"title_zh": "功", "title_en": "Work", "formula": "W = Fd cosθ", "note_zh": "力与位移夹角 θ。", "note_en": "Angle θ between force and displacement."},
        {"title_zh": "功率", "title_en": "Power", "formula": "P = W/t = Fv", "note_zh": "恒力同向时 P=Fv。", "note_en": "P=Fv when force aligns with velocity."},
        {"title_zh": "动量", "title_en": "Momentum", "formula": "p = mv", "note_zh": "孤立系统动量守恒。", "note_en": "Conserved in isolated systems."},
        {"title_zh": "冲量", "title_en": "Impulse", "formula": "J = FΔt = Δp", "note_zh": "力–时间改变动量。", "note_en": "Force–time changes momentum."},
        {"title_zh": "简谐振动周期", "title_en": "SHM period (spring)", "formula": "T = 2π√(m/k)", "note_zh": "质量与劲度系数。", "note_en": "Depends on mass and spring constant."},
        {"title_zh": "波速", "title_en": "Wave speed", "formula": "v = fλ", "note_zh": "频率 × 波长。", "note_en": "Frequency times wavelength."},
        {"title_zh": "库仑定律", "title_en": "Coulomb’s law", "formula": "F = kq₁q₂/r²", "note_zh": "点电荷静电力。", "note_en": "Electrostatic force between point charges."},
        {"title_zh": "欧姆定律", "title_en": "Ohm’s law", "formula": "V = IR", "note_zh": "线性导体适用。", "note_en": "For ohmic conductors."},
        {"title_zh": "电功率", "title_en": "Electric power", "formula": "P = IV = I²R = V²/R", "note_zh": "电路耗能速率。", "note_en": "Rate of energy use in circuits."},
        {"title_zh": "泊肃叶定律", "title_en": "Poiseuille’s law", "formula": "Q = πr⁴ΔP/(8ηL)", "note_zh": "层流管状血流。", "note_en": "Laminar flow in tubes/blood vessels."},
        {"title_zh": "伯努利方程", "title_en": "Bernoulli equation", "formula": "P + ½ρv² + ρgh = constant", "note_zh": "理想、定常、不可压缩流。", "note_en": "Ideal steady incompressible flow along streamline."},
        {"title_zh": "薄透镜", "title_en": "Thin lens", "formula": "1/f = 1/do + 1/di", "note_zh": "统一符号约定。", "note_en": "Keep sign conventions consistent."},
        {"title_zh": "光子能量", "title_en": "Photon energy", "formula": "E = hf = hc/λ", "note_zh": "量子与光电效应。", "note_en": "Quantum and photoelectric contexts."},
    ],
    "biochemistry": [
        {"title_zh": "米氏方程", "title_en": "Michaelis–Menten", "formula": "v = Vmax[S]/(Km + [S])", "note_zh": "酶促初速率。", "note_en": "Initial enzyme-catalyzed rate."},
        {"title_zh": "Lineweaver–Burk", "title_en": "Lineweaver–Burk", "formula": "1/v = (Km/Vmax)(1/[S]) + 1/Vmax", "note_zh": "双倒数作图求 Km、Vmax。", "note_en": "Double-reciprocal plot for Km and Vmax."},
        {"title_zh": "糖酵解净 ATP", "title_en": "Glycolysis net ATP", "formula": "2 ATP per glucose", "note_zh": "胞质；另产 2 NADH。", "note_en": "Cytoplasmic; also 2 NADH."},
        {"title_zh": "TCA 每乙酰 CoA", "title_en": "TCA per acetyl-CoA", "formula": "3 NADH + 1 FADH₂ + 1 GTP", "note_zh": "线粒体基质循环。", "note_en": "Mitochondrial matrix cycle."},
        {"title_zh": "氧化磷酸化 ATP", "title_en": "OxPhos ATP yield", "formula": "~2.5 ATP/NADH; ~1.5 ATP/FADH₂", "note_zh": "近似值；因质子漏而异。", "note_en": "Approximate; varies with proton leak."},
        {"title_zh": "脂肪酸氧化", "title_en": "β-oxidation", "formula": "n carbons → (n/2−1) FADH₂ + (n/2−1) NADH + n/2 acetyl-CoA", "note_zh": "偶数碳脂肪酸。", "note_en": "Even-chain fatty acids."},
        {"title_zh": "等电点", "title_en": "Isoelectric point", "formula": "pI ≈ (pKa₁ + pKa₂)/2", "note_zh": "两性离子氨基酸近似。", "note_en": "Approximation for dipolar amino acids."},
        {"title_zh": "ATP 水解", "title_en": "ATP hydrolysis", "formula": "ATP + H₂O → ADP + Pi; ΔG°′ ≈ −30 kJ/mol", "note_zh": "生物能货币。", "note_en": "Cellular energy currency."},
        {"title_zh": "血红蛋白氧合", "title_en": "Hb oxygen binding", "formula": "Sigmoid saturation curve", "note_zh": "协同结合；Bohr 效应。", "note_en": "Cooperative binding; Bohr effect."},
        {"title_zh": "糖原合成消耗", "title_en": "Glycogen synthesis cost", "formula": "1 glucose → glycogen costs 1 ATP + 1 UTP", "note_zh": "UDP-葡萄糖前体。", "note_en": "UDP-glucose precursor."},
        {"title_zh": "Cori 循环", "title_en": "Cori cycle", "formula": "Lactate (muscle) → glucose (liver)", "note_zh": "耗能再生葡萄糖。", "note_en": "Energy cost to regenerate glucose."},
        {"title_zh": "翻译能量", "title_en": "Translation energy", "formula": "~4 ATP per peptide bond (approx.)", "note_zh": "延伸步骤多步耗能。", "note_en": "Multiple steps per elongation cycle."},
    ],
    "chem-phys": [
        {"title_zh": "理想气体", "title_en": "Ideal gas", "formula": "PV = nRT", "note_zh": "Chem/Phys 气体与呼吸计算。", "note_en": "Gas and respiration calculations in Chem/Phys."},
        {"title_zh": "Henderson–Hasselbalch", "title_en": "Henderson–Hasselbalch", "formula": "pH = pKa + log([A⁻]/[HA])", "note_zh": "血液与缓冲生理。", "note_en": "Blood and buffer physiology."},
        {"title_zh": "米氏动力学", "title_en": "Michaelis–Menten", "formula": "v = Vmax[S]/(Km + [S])", "note_zh": "生化交叉题常见。", "note_en": "Common biochemistry crossover item."},
        {"title_zh": "吉布斯自由能", "title_en": "Gibbs free energy", "formula": "ΔG = ΔH − TΔS", "note_zh": "反应自发与平衡。", "note_en": "Spontaneity and equilibrium."},
        {"title_zh": "欧姆定律", "title_en": "Ohm’s law", "formula": "V = IR", "note_zh": "神经膜与电路类比。", "note_en": "Neural membrane and circuit analogies."},
        {"title_zh": "泊肃叶", "title_en": "Poiseuille", "formula": "Q ∝ r⁴ΔP/(ηL)", "note_zh": "血管半径对流量极敏感。", "note_en": "Vessel radius dominates flow sensitivity."},
        {"title_zh": "伯努利", "title_en": "Bernoulli", "formula": "P + ½ρv² + ρgh = const.", "note_zh": "血流与气道流体。", "note_en": "Blood flow and airway fluids."},
        {"title_zh": "能斯特", "title_en": "Nernst", "formula": "E = E° − (RT/nF) ln Q", "note_zh": "膜电位与电化学电池。", "note_en": "Membrane potentials and electrochemical cells."},
        {"title_zh": "斯涅尔定律", "title_en": "Snell’s law", "formula": "n₁sinθ₁ = n₂sinθ₂", "note_zh": "光学与内窥镜。", "note_en": "Optics and endoscopy contexts."},
        {"title_zh": "光子能量", "title_en": "Photon energy", "formula": "E = hf", "note_zh": "光谱与光电效应。", "note_en": "Spectroscopy and photoelectric effect."},
        {"title_zh": "RC 时间常数", "title_en": "RC time constant", "formula": "τ = RC", "note_zh": "膜电容充放电。", "note_en": "Membrane capacitance charge/discharge."},
        {"title_zh": "功–能定理", "title_en": "Work–energy theorem", "formula": "W_net = ΔKE", "note_zh": "肌肉与骨骼力学。", "note_en": "Musculoskeletal mechanics."},
        {"title_zh": "半衰期", "title_en": "Half-life", "formula": "N = N₀(½)^(t/t½)", "note_zh": "核医学同位素。", "note_en": "Nuclear medicine isotopes."},
        {"title_zh": "Beer 定律", "title_en": "Beer’s law", "formula": "A = εlc", "note_zh": "分光测定浓度。", "note_en": "Spectrophotometric concentration."},
        {"title_zh": "阿伦尼乌斯", "title_en": "Arrhenius", "formula": "k = Ae^(−Ea/RT)", "note_zh": "温度对速率常数。", "note_en": "Temperature effect on rate constant."},
    ],
    "bio-biochem": [
        {"title_zh": "哈迪–温伯格", "title_en": "Hardy–Weinberg", "formula": "p² + 2pq + q² = 1", "note_zh": "群体遗传 FC1C。", "note_en": "Population genetics in FC1C."},
        {"title_zh": "米氏方程", "title_en": "Michaelis–Menten", "formula": "v = Vmax[S]/(Km + [S])", "note_zh": "FC1A 酶动力学。", "note_en": "FC1A enzyme kinetics."},
        {"title_zh": "糖酵解净 ATP", "title_en": "Glycolysis net", "formula": "2 ATP + 2 NADH per glucose", "note_zh": "FC1D 代谢。", "note_en": "FC1D metabolism."},
        {"title_zh": "TCA 产出", "title_en": "TCA output", "formula": "3 NADH + 1 FADH₂ + 1 GTP / acetyl-CoA", "note_zh": "与氧化磷酸化偶联。", "note_en": "Coupled to oxidative phosphorylation."},
        {"title_zh": "心输出量", "title_en": "Cardiac output", "formula": "CO = HR × SV", "note_zh": "FC3B 循环。", "note_en": "FC3B circulation."},
        {"title_zh": "膜电位", "title_en": "Membrane potential", "formula": "ΔV ∝ Δion flux / capacitance", "note_zh": "FC3A 神经。", "note_en": "FC3A neural signaling."},
        {"title_zh": "稀释", "title_en": "Dilution", "formula": "C₁V₁ = C₂V₂", "note_zh": "实验设计稀释系列。", "note_en": "Experimental dilution series."},
        {"title_zh": "重组率", "title_en": "Recombination frequency", "formula": "RF = recombinants / total", "note_zh": "FC1C 连锁。", "note_en": "FC1C linkage mapping."},
        {"title_zh": "渗透压", "title_en": "Osmotic pressure", "formula": "π = iMRT", "note_zh": "细胞容积调节。", "note_en": "Cell volume regulation."},
        {"title_zh": "ATP 水解", "title_en": "ATP hydrolysis", "formula": "ΔG°′ ≈ −30 kJ/mol", "note_zh": "生物能学核心。", "note_en": "Core bioenergetics."},
        {"title_zh": "氧合曲线", "title_en": "Oxygen saturation", "formula": "Sigmoid PO₂–Sat curve", "note_zh": "Hb 协同与 Bohr。", "note_en": "Hb cooperativity and Bohr."},
        {"title_zh": "细胞周期", "title_en": "Cell cycle duration", "formula": "T = G₁ + S + G₂ + M", "note_zh": "FC2C 分裂调控。", "note_en": "FC2C division control."},
        {"title_zh": "翻译密码子", "title_en": "Genetic code", "formula": "64 codons → 20 aa + stop", "note_zh": "FC1B 简并。", "note_en": "FC1B degeneracy."},
        {"title_zh": "抗体多样性", "title_en": "Antibody diversity", "formula": "V(D)J recombination combinatorics", "note_zh": "FC3B 免疫。", "note_en": "FC3B immunity."},
    ],
    "quantitative": [
        {"title_zh": "百分比变化", "title_en": "Percent change", "formula": "%Δ = (new − old) / old × 100%", "note_zh": "区分百分点与百分比。", "note_en": "Distinct from percentage points."},
        {"title_zh": "比例", "title_en": "Proportion", "formula": "a/b = c/d → ad = bc", "note_zh": "交叉相乘前统一单位。", "note_en": "Cross-multiply after unit alignment."},
        {"title_zh": "平均速度", "title_en": "Average speed", "formula": "v_avg = total distance / total time", "note_zh": "不同于瞬时速度。", "note_en": "Distinct from instantaneous speed."},
        {"title_zh": "平均数", "title_en": "Mean", "formula": "x̄ = Σx / n", "note_zh": "受极端值影响。", "note_en": "Sensitive to outliers."},
        {"title_zh": "中位数", "title_en": "Median", "formula": "middle of ordered data", "note_zh": "偶数个取中间两数平均。", "note_en": "Average middle two if even count."},
        {"title_zh": "折扣价", "title_en": "Discount price", "formula": "sale = original × (1 − discount%)", "note_zh": "连续折扣不可简单相加。", "note_en": "Sequential discounts don’t add simply."},
        {"title_zh": "复利", "title_en": "Compound interest", "formula": "A = P(1 + r/n)^(nt)", "note_zh": "注意计息周期 n。", "note_en": "Watch compounding periods n."},
        {"title_zh": "利润率", "title_en": "Profit margin", "formula": "margin = profit / revenue", "note_zh": "分母是收入非成本。", "note_en": "Denominator is revenue, not cost."},
    ],
    "behavioral-social": [
        {"title_zh": "韦伯定律", "title_en": "Weber’s law", "formula": "ΔI/I = k", "note_zh": "可觉差与刺激强度成比例。", "note_en": "Detectable difference scales with intensity."},
        {"title_zh": "费希纳定律", "title_en": "Fechner’s law", "formula": "S = k log I", "note_zh": "感知强度与刺激对数相关。", "note_en": "Perceived intensity logs stimulus strength."},
        {"title_zh": "相关系数", "title_en": "Correlation", "formula": "r ∈ [−1, 1]", "note_zh": "描述线性关系方向与强度。", "note_en": "Direction and strength of linear relation."},
        {"title_zh": "z 分数", "title_en": "z-score", "formula": "z = (x − μ) / σ", "note_zh": "标准化比较不同量纲。", "note_en": "Standardize across scales."},
        {"title_zh": "观察学习概率", "title_en": "Social learning", "formula": "P(behavior) ↑ after modeled reward", "note_zh": "班杜拉观察学习。", "note_en": "Bandura observational learning."},
    ],
    "psych-soc": [
        {"title_zh": "韦伯定律", "title_en": "Weber’s law", "formula": "ΔI/I = constant", "note_zh": "FC6A 感觉。", "note_en": "FC6A sensation."},
        {"title_zh": "信号检测", "title_en": "Signal detection", "formula": "d′ = Z(hit) − Z(false alarm)", "note_zh": "区分灵敏度与反应偏向。", "note_en": "Separates sensitivity from response bias."},
        {"title_zh": "相关系数", "title_en": "Correlation", "formula": "r ∈ [−1, 1]", "note_zh": "研究设计题。", "note_en": "Research-design items."},
        {"title_zh": "z 分数", "title_en": "z-score", "formula": "z = (x − μ) / σ", "note_zh": "标准化分数。", "note_en": "Standardized scores."},
        {"title_zh": "自我效能", "title_en": "Self-efficacy", "formula": "behavior ∝ perceived capability", "note_zh": "FC7 行为改变。", "note_en": "FC7 behavior change."},
        {"title_zh": "从众比例", "title_en": "Conformity rate", "formula": "compliance ↑ with unanimous majority", "note_zh": "FC7B 社会过程。", "note_en": "FC7B social processes."},
    ],
}

EXAM_TIPS: list[dict[str, str]] = [
    {
        "exam": "NMAT",
        "title_zh": "Part 1 时间分配",
        "title_en": "Part 1 time budget",
        "body_zh": "CEM BOI 建议：Verbal ~30 分、Inductive ~35 分、Quantitative ~40 分、Perceptual ~30 分。先按建议计时练整套，再微调弱项。",
        "body_en": "CEM BOI pacing: Verbal ~30 min, Inductive ~35 min, Quantitative ~40 min, Perceptual ~30 min. Practice full Part 1 on those clocks, then adjust for weak areas.",
    },
    {
        "exam": "NMAT",
        "title_zh": "Part 2 四科轮转",
        "title_en": "Part 2 four-subject rotation",
        "body_zh": "Biology、Physics、Social Science、Chemistry 各 30 题共 90 分钟。不要在一科耗尽时间；每题平均约 45 秒，难题先标记再回看。",
        "body_en": "Biology, Physics, Social Science, Chemistry — 30 items each in 90 minutes. Don’t drain time on one subject; ~45 s per item average, mark hard ones and return.",
    },
    {
        "exam": "NMAT",
        "title_zh": "Social Science 范围",
        "title_en": "Social Science scope",
        "body_zh": "CEM 明确包含 Psychology 与 Sociology and Anthropology，不是纯心理学。人类学文化视角题会出现，按 BOI 两章复习。",
        "body_en": "CEM lists Psychology plus Sociology and Anthropology — not psychology alone. Anthropology culture items appear; study both BOI blocks.",
    },
    {
        "exam": "NMAT",
        "title_zh": "生化在 Chemistry 内",
        "title_en": "Biochemistry inside Chemistry",
        "body_zh": "NMAT 无独立 Biochemistry 科；CEM 将其列在 Chemistry 的 Biochemistry 块。与 MCAT Bio/Biochem 重叠部分可共用 Gabay 生化章节。",
        "body_en": "NMAT has no separate Biochemistry subtest; CEM nests it under Chemistry. Overlap with MCAT Bio/Biochem can share Gabay biochemistry chapters.",
    },
    {
        "exam": "MCAT",
        "title_zh": "考试日四科顺序",
        "title_en": "Test-day section order",
        "body_zh": "AAMC 固定顺序：Chem/Phys → CARS → Bio/Biochem → Psych/Soc。每科中间约 10 分钟可选休息。模考按此顺序练耐力。",
        "body_en": "AAMC fixed order: Chem/Phys → CARS → Bio/Biochem → Psych/Soc, with optional ~10-minute breaks. Simulate endurance in that order.",
    },
    {
        "exam": "MCAT",
        "title_zh": "Chem/Phys FC 权重",
        "title_en": "Chem/Phys FC weighting",
        "body_zh": "AAMC 在该科内 FC4（物理相关）约 40%、FC5（化学相关）约 60%。Gabay 按官方 Content Categories 4A–5E 分章，不按备考百分比拆页。",
        "body_en": "AAMC weights FC4 ~40% and FC5 ~60% within Chem/Phys. Gabay chapters follow official Content Categories 4A–5E, not prep-percent splits.",
    },
    {
        "exam": "MCAT",
        "title_zh": "Bio/Biochem FC 权重",
        "title_en": "Bio/Biochem FC weighting",
        "body_zh": "AAMC：FC1 ~55%、FC2 ~20%、FC3 ~25%。生化 FC1（1A–1D）权重最高；与 NMAT Chemistry·Biochemistry 块可交叉复习。",
        "body_en": "AAMC: FC1 ~55%, FC2 ~20%, FC3 ~25%. Biochemistry-heavy FC1 (1A–1D) dominates; cross-review with NMAT Chemistry·Biochemistry.",
    },
    {
        "exam": "MCAT",
        "title_zh": "Psych/Soc 人类学定位",
        "title_en": "Anthropology on Psych/Soc",
        "body_zh": "MCAT Psych/Soc 以心理学与社会学为主（AAMC FC6–10）；人类学不是 NMAT 式独立主轴。文化差异在 FC9 等类别出现。",
        "body_en": "MCAT Psych/Soc emphasizes psychology and sociology (AAMC FC6–10); anthropology isn’t a separate axis like NMAT. Cultural content appears in FC9 categories.",
    },
    {
        "exam": "MCAT",
        "title_zh": "CARS 无内容大纲",
        "title_en": "CARS has no content outline",
        "body_zh": "CARS 按 AAMC 三技能轴：Foundations、Within the Text、Beyond the Text。不需背学科事实；练篇章节奏与证据定位。",
        "body_en": "CARS follows AAMC’s three skills: Foundations, Within the Text, Beyond the Text. No science memorization — train passage pacing and evidence location.",
    },
    {
        "exam": "BOTH",
        "title_zh": "Gabay 共用科目页",
        "title_en": "Gabay shared subject pages",
        "body_zh": "Biology、Chemistry、Physics、Behavioral-Social 在 NMAT Part 2 与 MCAT 多科共用。章节标题合并 CEM BOI 与 AAMC Content Categories，避免重复建第九科。",
        "body_en": "Biology, Chemistry, Physics, and Behavioral-Social are shared across NMAT Part 2 and multiple MCAT sections. Chapters merge CEM BOI and AAMC categories without inventing extra subjects.",
    },
    {
        "exam": "BOTH",
        "title_zh": "篇章 vs 独立题",
        "title_en": "Passage vs standalone items",
        "body_zh": "NMAT 以独立选择题为主；MCAT 科学三科大量篇章题（每段多题）。MCAT 练读图、实验设计与数据表；NMAT 练速度与广覆盖。",
        "body_en": "NMAT is mostly standalone multiple choice; MCAT science sections are passage-heavy. MCAT trains graphs, experimental design, and data tables; NMAT trains speed and breadth.",
    },
    {
        "exam": "BOTH",
        "title_zh": "先官方大纲再刷题",
        "title_en": "Outline before drill",
        "body_zh": "以 CEM BOI 与 AAMC What’s on the MCAT 为章节目录；笔记与练习挂在官方章节下，不凭空加“第 X 章”伪标题。",
        "body_en": "Use CEM BOI and AAMC What’s on the MCAT as the chapter spine; notes and practice attach to official headings — no invented pseudo-chapters.",
    },
    {
        "exam": "BOTH",
        "title_zh": "双语笔记用法",
        "title_en": "Using bilingual notes",
        "body_zh": "Gabay 笔记中英对照：先读中文抓要点，再用英文核对考试常用表述。MCAT 题干为英文，NMAT 亦大量英文题干。",
        "body_en": "Gabay notes are bilingual: grasp points in Chinese, then verify exam phrasing in English. MCAT is English; NMAT stems are largely English too.",
    },
    {
        "exam": "MCAT",
        "title_zh": "科学科读题顺序",
        "title_en": "Science section reading order",
        "body_zh": "篇章题可先扫图表与问题干，再回文定位；纯概念题直接做。95 分钟内 59 题，留 5–8 分钟检查标记题。",
        "body_en": "For passages, skim figures and question stems first, then locate evidence; tackle standalone concept items directly. In 95 minutes for 59 items, reserve 5–8 min for marked questions.",
    },
]

STUDY_PATHS: list[dict[str, str | list[dict[str, str]]]] = [
    {
        "id": "nmat-part1-week",
        "title_zh": "NMAT Part 1 一周冲刺",
        "title_en": "NMAT Part 1 one-week sprint",
        "blurb_zh": "按 CEM BOI 四科心智能力：每天一科精练 + 隔天全套计时。",
        "blurb_en": "CEM BOI mental-ability blocks: one subject deep drill daily plus timed full Part 1 every other day.",
        "steps": [
            {"label_zh": "语文 Verbal", "label_en": "Verbal", "href": "/subjects/verbal/"},
            {"label_zh": "归纳推理", "label_en": "Inductive Reasoning", "href": "/subjects/inductive-reasoning/"},
            {"label_zh": "数量推理", "label_en": "Quantitative", "href": "/subjects/quantitative/"},
            {"label_zh": "知觉敏锐", "label_en": "Perceptual Acuity", "href": "/subjects/perceptual-acuity/"},
            {"label_zh": "Part 1 练习", "label_en": "Part 1 practice", "href": "/practice/verbal/"},
        ],
    },
    {
        "id": "nmat-part2-sciences",
        "title_zh": "NMAT Part 2 理科四科",
        "title_en": "NMAT Part 2 sciences",
        "blurb_zh": "Biology、Physics、Social Science、Chemistry 各 30 题。按 BOI 章节笔记 + 分科练习。",
        "blurb_en": "Biology, Physics, Social Science, Chemistry — 30 items each. BOI-chapter notes plus per-subject practice.",
        "steps": [
            {"label_zh": "生物学", "label_en": "Biology", "href": "/subjects/biology/"},
            {"label_zh": "物理学", "label_en": "Physics", "href": "/subjects/physics/"},
            {"label_zh": "社会科学", "label_en": "Social Science", "href": "/subjects/behavioral-social/"},
            {"label_zh": "化学", "label_en": "Chemistry", "href": "/subjects/chemistry/"},
            {"label_zh": "生物练习", "label_en": "Biology practice", "href": "/practice/biology/"},
        ],
    },
    {
        "id": "mcat-science-core",
        "title_zh": "MCAT 科学三科核心",
        "title_en": "MCAT science core",
        "blurb_zh": "Chem/Phys、Bio/Biochem、Psych/Soc 按 AAMC FC 章节推进；共用 Biology/Chemistry/Physics 笔记打底。",
        "blurb_en": "Chem/Phys, Bio/Biochem, Psych/Soc along AAMC FC chapters; shared Biology/Chemistry/Physics notes as foundation.",
        "steps": [
            {"label_zh": "Chem/Phys", "label_en": "Chem/Phys", "href": "/subjects/chem-phys/"},
            {"label_zh": "Bio/Biochem", "label_en": "Bio/Biochem", "href": "/subjects/bio-biochem/"},
            {"label_zh": "Psych/Soc", "label_en": "Psych/Soc", "href": "/subjects/psych-soc/"},
            {"label_zh": "生物化学", "label_en": "Biochemistry", "href": "/subjects/biochemistry/"},
            {"label_zh": "Chem/Phys 练习", "label_en": "Chem/Phys practice", "href": "/practice/chem-phys/"},
        ],
    },
    {
        "id": "cars-verbal-skills",
        "title_zh": "CARS + 语文技能",
        "title_en": "CARS and verbal skills",
        "blurb_zh": "MCAT CARS 三技能轴 + NMAT Verbal 类比与阅读；强调证据与关系，不背学科事实。",
        "blurb_en": "MCAT CARS three skill axes plus NMAT Verbal analogies and reading — evidence and relations, not science facts.",
        "steps": [
            {"label_zh": "CARS", "label_en": "CARS", "href": "/subjects/cars/"},
            {"label_zh": "语文 Verbal", "label_en": "Verbal", "href": "/subjects/verbal/"},
            {"label_zh": "CARS 练习", "label_en": "CARS practice", "href": "/practice/cars/"},
            {"label_zh": "语文练习", "label_en": "Verbal practice", "href": "/practice/verbal/"},
        ],
    },
    {
        "id": "biochem-bridge",
        "title_zh": "生化桥梁（NMAT↔MCAT）",
        "title_en": "Biochemistry bridge (NMAT↔MCAT)",
        "blurb_zh": "从 NMAT Chemistry·Biochemistry 到 MCAT FC1（1A–1D）与 FC1D 代谢；一套笔记两边用。",
        "blurb_en": "From NMAT Chemistry·Biochemistry to MCAT FC1 (1A–1D) and FC1D metabolism — one note set for both exams.",
        "steps": [
            {"label_zh": "化学（含生化块）", "label_en": "Chemistry (biochem block)", "href": "/subjects/chemistry/"},
            {"label_zh": "生物化学专题", "label_en": "Biochemistry", "href": "/subjects/biochemistry/"},
            {"label_zh": "Bio/Biochem", "label_en": "Bio/Biochem", "href": "/subjects/bio-biochem/"},
            {"label_zh": "生化练习", "label_en": "Biochemistry practice", "href": "/practice/biochemistry/"},
        ],
    },
]
