"""Auto-applied ZH→EN strings for Gabay UI/content."""
ZH_EN = {
    'AAMC 估计 Bio/Biochem 中 FC1 约占该科 55%（约到 5%）。': 'AAMC estimates FC1 is about 55% of Bio/Biochem (rounded to 5%).',
    'Chem/Phys 侧重普化/有机/相互作用；Bio/Biochem 侧重生化分子与代谢。': 'Chem/Phys emphasizes gen/organic chem and interactions; Bio/Biochem emphasizes biomolecules and metabolism.',
    'MCAT Bio/Biochem 主体，并少量出现在 Chem/Phys': 'Core of MCAT Bio/Biochem; also appears lightly in Chem/Phys',
    'MCAT Chem/Phys + Bio/Biochem 中的化学 / 生化内容': 'Chemistry/biochem content inside MCAT Chem/Phys and Bio/Biochem',
    'MCAT Chem/Phys 中的物理学（AAMC FC4）': 'Physics within MCAT Chem/Phys (AAMC FC4)',
    'MCAT 高权重专题；NMAT 不单开此科，CEM 将其放在 Chemistry 的 Biochemistry。': 'High-weight MCAT topic; not a separate NMAT subtest — CEM places it under Chemistry → Biochemistry.',
    'NMAT Part 2 · Biology（30 题）': 'NMAT Part 2 · Biology (30 items)',
    'NMAT Part 2 · Chemistry（30 题）': 'NMAT Part 2 · Chemistry (30 items)',
    'NMAT Part 2 · Physics（30 题）': 'NMAT Part 2 · Physics (30 items)',
    'NMAT 五块标题取自 CEM BOI Physics；MCAT 侧对应 AAMC Foundational Concept 4。': 'NMAT headings from CEM BOI Physics; MCAT side maps to AAMC Foundational Concept 4.',
    'NMAT 四块标题取自 CEM BOI Chemistry；MCAT 侧对应 AAMC FC5 及生化交叉类别。': 'NMAT headings from CEM BOI Chemistry; MCAT side maps to AAMC FC5 and biochem overlaps.',
    'NMAT 按 CEM BOI：Psychology + Sociology and Anthropology。MCAT 按 AAMC FC6–10。': 'NMAT per CEM BOI: Psychology + Sociology and Anthropology. MCAT per AAMC FC6–10.',
    'NMAT 章节标题直接取自 CEM BOI Part 2 Biology；MCAT 侧列出与生物重叠的 AAMC Content Categories。': 'NMAT chapter titles from CEM BOI Part 2 Biology; MCAT lists overlapping AAMC Content Categories.',
    'Social Science = psychology + sociology + anthropology，导论深度。': 'Social Science = psychology + sociology + anthropology at intro depth.',
    '不要当成第九科；跟 Chemistry · Biochemistry 一起复习。': 'Not a 9th subtest — review with Chemistry · Biochemistry.',
    '与代谢相关的基本概念（详见 Biochemistry 专题页）': 'Basic metabolism ideas (see Biochemistry hub)',
    '与导论化学衔接的代谢基本概念': 'Intro metabolism concepts linked to intro chemistry',
    '与生物分子相关的有机基础': 'Organic foundations relevant to biomolecules',
    '与生物化学交织；大量篇章题，强调实验设计与数据推理。': 'Interwoven with biochem; many passage items; research design and data reasoning.',
    '两部分共 240 道选择题；每科 30 题。Part 1 心智能力 2h15m，Part 2 学业能力 1h30m，中间约 10 分钟休息。': 'Two parts, 240 MCQs, 30 per subtest. Part 1 mental ability 2h15m; Part 2 academic 1h30m; ~10-minute break.',
    '主要器官系统的结构与整合功能': 'Structure and integrative functions of major organ systems',
    '主要落在 Bio/Biochem FC1，并与 Chem/Phys 生化交叉': 'Primarily Bio/Biochem FC1, with Chem/Phys biochem overlap',
    '人口特征与过程': 'Demographic characteristics and processes',
    '人类学基本视角（NMAT 明确包含）': 'Basic anthropology perspectives (explicitly in NMAT)',
    '从有限信息归纳规则或关系。': 'Infer rules or relations from limited information.',
    '以心理、社会为主，并带少量生物基础；人类学不是独立主轴。': 'Mostly psych/soc with some biology; anthropology is not a separate MCAT spine.',
    '位置、阴影、叠加规则归纳': 'Infer rules of position, shading, and overlays',
    '光、声与物质的相互作用': 'How light and sound interact with matter',
    '光、声与物质相互作用': 'Light and sound interacting with matter',
    '全篇章题；不要求特定学科内容知识，考理解与推理。': 'All passage-based; no required content knowledge — comprehension and reasoning.',
    '共同属性归组': 'Group by shared attributes',
    '共用': 'Shared',
    '内环境维持': 'Maintaining the internal environment',
    '几何/波动光学基础': 'Basics of geometric/wave optics',
    '分子、细胞与细胞群的组装': 'Assemblies of molecules, cells, and cell groups',
    '分子与分子间作用': 'Molecules and intermolecular interactions',
    '分子本质与分子间作用': 'Nature of molecules and intermolecular forces',
    '分数/百分数/比与比例速算': 'Quick work with fractions, percents, ratios',
    '分离与纯化': 'Separation and purification',
    '分离纯化（含肽/蛋白相关方法）': 'Separations/purifications (including peptide/protein methods)',
    '分类与演化导论概念': 'Intro ideas in classification and evolution',
    '分裂、分化与特化': 'Division, differentiation, and specialization',
    '判断类推是否成立': 'Judge whether an analogy holds',
    '力学到近代物理的导论框架；NMAT 独立成科，MCAT 主要落在 Chem/Phys。': 'Intro arc from mechanics to modern physics; separate NMAT subtest; mainly Chem/Phys on MCAT.',
    '化学热力学与动力学': 'Chemical thermodynamics and kinetics',
    '化学键与计量': 'Bonding and stoichiometry',
    '单位换算与合理性检查': 'Unit conversion and reasonableness checks',
    '单细胞与多细胞组装层次': 'Organization from single cells to multicellular assemblies',
    '原子、核衰变、电子结构与原子化学行为': 'Atoms, nuclear decay, electronic structure, and atomic chemical behavior',
    '原子、核衰变与电子结构': 'Atoms, nuclear decay, and electronic structure',
    '原子化学行为（Chem/Phys）': 'Atomic chemical behavior (Chem/Phys)',
    '原子结构与周期性': 'Atomic structure and periodicity',
    '原核生物与病毒的结构、生长、生理与遗传': 'Structure, growth, physiology, and genetics of prokaryotes and viruses',
    '发育过程基本概念': 'Basic developmental concepts',
    '变异与遗传规律导论': 'Intro variation and inheritance patterns',
    '可合并': 'Mergeable',
    '四个官方科目；科学三科各 59 题 / 95 分钟，CARS 53 题 / 90 分钟。考试日顺序固定。': 'Four official sections; three science sections 59 Q / 95 min; CARS 53 Q / 90 min; fixed test-day order.',
    '四则与优先级': 'Four operations and order of operations',
    '在复杂图中定位目标轮廓': 'Find a target outline in a complex figure',
    '增加遗传多样性的过程': 'Processes that increase genetic diversity',
    '大学导论物理学。章节见共用科目页。': 'Intro college physics. See shared subject page for chapters.',
    '大学导论物理常见主题，强调概念与推理。': 'Typical intro physics themes; concepts and reasoning.',
    '大学导论生物学。章节见共用科目页。': 'Intro college biology. See shared subject page for chapters.',
    '字母位置与双序列穿插': 'Letter positions and interleaved dual series',
    '学科百分比为常见备考分解；Foundational Concept 占比取自 AAMC What’s on the MCAT（约到 5%，不同卷会浮动）。': 'Discipline % from common prep breakdowns; FC shares from AAMC What’s on the MCAT (~5%, form-to-form variation).',
    '官能团与基本反应类型': 'Functional groups and basic reaction types',
    '定量分析基础': 'Basics of quantitative analysis',
    '对世界作出反应': 'Responding to the world',
    '对标大学导论级生物学；偏概念与综合认知（理解、应用、分析）。': 'Aligned to intro biology; concepts plus understanding/applying/analyzing.',
    '导论心理学概念': 'Introductory psychology concepts',
    '导论课范围：普化、分析、有机、生化常见基本概念。': 'Intro scope: common gen/analytical/organic/biochem ideas.',
    '左右镜像判断': 'Left-right mirror judgments',
    '常嵌在生理/医疗情境篇章里，少纯算、多关系与估算。': 'Often embedded in physio/clinical passages; less pure calc, more relations and estimation.',
    '常见分离/测定思路（导论级）': 'Common separation/assay ideas (intro level)',
    '干扰条件下的视觉识别、细节与空间关系。': 'Visual recognition, detail, and spatial relations under distraction.',
    '平衡与动量导论': 'Intro equilibrium and momentum',
    '影响行为的个体因素': 'Individual influences on behavior',
    '影响行为的社会过程': 'Social processes that influence behavior',
    '心理 / 社会与人类学导论。章节见共用科目页。': 'Intro psych / sociology & anthropology. See shared subject page.',
    '心理、社会、人类学交叉；NMAT 叫 Social Science，MCAT 对应 Psych/Soc。': 'Psych, sociology, anthropology overlap; NMAT Social Science ↔ MCAT Psych/Soc.',
    '快速比对相同/差异': 'Quick same/different comparisons',
    '态度与行为改变': 'Attitude and behavior change',
    '感觉环境': 'Sensing the environment',
    '把关系迁移到选项，排除貌合神离干扰项': 'Transfer the relation to choices; eliminate look-alike distractors',
    '把原则应用到新情境': 'Apply a principle to a new situation',
    '把握作者态度与论证基调': 'Track author attitude and argumentative tone',
    '把文字转成数量关系': 'Turn word problems into quantitative relations',
    '把普化、有机、物理、生化放进生命系统情境里考。': 'Test gen/organic chem, physics, and biochem in living-system contexts.',
    '抓主旨与段落功能': 'Capture main idea and paragraph function',
    '抗干扰与局部匹配': 'Resist distraction; match local features',
    '振动与波': 'Vibrations and waves',
    '排除唯一例外': 'Exclude the odd one out',
    '推断文内隐含但可支持的结论': 'Infer supported but unstated conclusions in-text',
    '整合文外信息时仍忠于文本约束': 'Integrate outside info without violating the passage',
    '旋转/翻转/增减元素': 'Rotation/reflection/add-remove elements',
    '普化、分析、有机与生化基础；NMAT 独立成科，MCAT 拆进 Chem/Phys 与 Bio/Biochem。': 'Gen/analytical/organic/biochem basics; own NMAT subtest; split across Chem/Phys and Bio/Biochem on MCAT.',
    '普化、分析、有机与生化导论。章节见共用科目页。': 'Intro gen/analytical/organic/biochem. See shared subject page.',
    '植物与动物世界导论': 'Intro world of plants and animals',
    '比较、趋势与简单统计推理': 'Comparisons, trends, and simple stats reasoning',
    '比较结构/功能常见考点': 'Common structure/function comparison points',
    '氨基酸与蛋白质结构/功能': 'Amino acid and protein structure/function',
    '水及其溶液': 'Water and its solutions',
    '水的独特性与溶液性质': 'Unique properties of water and solutions',
    '温度、热量与热力学定律导论': 'Intro temperature, heat, and thermo laws',
    '热力学与动力学原则': 'Principles of thermodynamics and kinetics',
    '独有': 'Unique',
    '理解/组织环境信息': 'Making sense of / organizing environmental information',
    '理解主旨与主要观点': 'Understand main idea and key claims',
    '理解社会结构': 'Understanding social structure',
    '生命的统一性与多样性': 'Unity and diversity of life',
    '生命系统中的平动、力、功、能与平衡': 'Translational motion, forces, work, energy, and equilibrium in living systems',
    '生命系统中的生物与生化，强调过程、实验与数据。': 'Biology/biochem in living systems — processes, experiments, and data.',
    '生态关系导论': 'Intro ecological relationships',
    '生物与环境': 'Organisms and their environment',
    '生物大分子导论': 'Intro biological macromolecules',
    '生物相关分子的结构、功能与反应性': 'Structure, function, and reactivity of biologically relevant molecules',
    '生物能学与燃料分子代谢': 'Bioenergetics and fuel molecule metabolism',
    '电化学与电路元件': 'Electrochemistry and circuit elements',
    '电场、电路基础': 'Basics of electric fields and circuits',
    '磁学导论': 'Intro magnetism',
    '社会不平等与资源可及性': 'Social inequality and access to resources',
    '社会互动': 'Social interactions',
    '社会思维': 'Social thinking',
    '社会结构与文化导论': 'Intro social structure and culture',
    '神经/内分泌如何协调器官系统': 'How nervous/endocrine systems coordinate organs',
    '神经与内分泌系统如何协调器官系统': 'How nervous and endocrine systems coordinate organ systems',
    '章节 = AAMC Foundational Concepts 1–3 及全部 Content Categories。': 'Chapters = AAMC Foundational Concepts 1–3 and all Content Categories.',
    '章节 = AAMC Foundational Concepts 4–5 及全部 Content Categories。': 'Chapters = AAMC Foundational Concepts 4–5 and all Content Categories.',
    '章节 = AAMC Foundational Concepts 6–10 及全部 Content Categories。': 'Chapters = AAMC Foundational Concepts 6–10 and all Content Categories.',
    '章节按 AAMC Bio/Biochem Foundational Concept 1 的 Content Categories；NMAT 仅作 Chemistry 子块对照。': 'Chapters follow AAMC Bio/Biochem FC1 Content Categories; NMAT only as Chemistry sub-block.',
    '章节按 AAMC CARS 三大技能轴展开（无学科内容大纲）。': 'Chapters follow AAMC CARS three skill axes (no content syllabus).',
    '章节按 CEM BOI Inductive Reasoning 题型划分。': 'Chapters follow CEM BOI Inductive Reasoning item types.',
    '章节按 CEM BOI Perceptual Acuity 题型划分。': 'Chapters follow CEM BOI Perceptual Acuity item types.',
    '章节按 CEM BOI Quantitative 题型划分。': 'Chapters follow CEM BOI Quantitative item types.',
    '章节按 CEM BOI Verbal 题型划分。': 'Chapters follow CEM BOI Verbal item types.',
    '等差/倍比/交替规则': 'Arithmetic/geometric/alternating rules',
    '组织并应用基础数学与推理求解。': 'Organize and apply basic math and reasoning to solve.',
    '细胞、遗传、稳态、生态与生命过程；两边都会考，深度与题型不同。': 'Cells, genetics, homeostasis, ecology, life processes — both exams, different depth/item style.',
    '细胞分裂、分化与特化': 'Cell division, differentiation, and specialization',
    '细胞结构与功能': 'Cell structure and function',
    '细胞过程（代谢、膜转运等导论级）': 'Cellular processes (intro metabolism, membrane transport, etc.)',
    '细节定位与推断（不超出文本）': 'Detail location and inference (stay inside the text)',
    '细节精度与速度权衡': 'Trade-off between detail accuracy and speed',
    '结构、功能与反应性': 'Structure, function, and reactivity',
    '结构、生长、生理与遗传': 'Structure, growth, physiology, and genetics',
    '翻转 vs 旋转区分': 'Distinguish flip vs rotation',
    '自我认同': 'Self-identity',
    '蛋白质及其组成氨基酸的结构与功能': 'Structure and function of proteins and their amino acids',
    '血液循环、气体运动与交换中的流体': 'Fluids in circulation, gas movement, and gas exchange',
    '血液循环与气体交换中的流体': 'Fluids in blood circulation and gas exchange',
    '行为与心理过程基础': 'Basics of behavior and mental processes',
    '行为的心理、社会与生物基础。': 'Psychological, social, and biological foundations of behavior.',
    '表/图读取': 'Read tables/graphs',
    '评估论证强度与相关性': 'Evaluate argument strength and relevance',
    '识别信息的作用（例证、定义、转折）': 'Identify roles of information (example, definition, turn)',
    '识别假设与逻辑关系': 'Identify assumptions and logical links',
    '识别词对关系（同义、反义、部分-整体、因果、程度等）': 'Identify word-pair relations (synonym, antonym, part-whole, cause, degree, etc.)',
    '词汇关系与阅读理解。': 'Lexical relations and reading comprehension.',
    '语气/态度与论证结构': 'Tone/attitude and argument structure',
    '调节与稳态': 'Regulation and homeostasis',
    '跨代遗传': 'Transmission across generations',
    '跨代遗传与增加遗传多样性的过程': 'Heritable transmission and processes that increase diversity',
    '跨代遗传与遗传多样性过程': 'Heritable information and genetic diversity processes',
    '运动、力、功与能': 'Motion, forces, work, and energy',
    '近代物理导论概念（如量子/核现象入门）': 'Intro modern physics (e.g., quantum/nuclear basics)',
    '进入共用科目页': 'Open shared subject page',
    '遗传信息从基因到蛋白质': 'Genetic information from gene to protein',
    '遗传信息从基因到蛋白质的传递': 'Transmission of genetic information from gene to protein',
    '遗传信息传递': 'Transmission of genetic information',
    '酸碱、氧化还原、平衡导论': 'Intro acids/bases, redox, and equilibrium',
    '非独立分测验；归入 Part 2 Chemistry · Biochemistry': 'Not a standalone subtest; under Part 2 Chemistry · Biochemistry',
    '题': 'items',
}

def t(text: str) -> str:
    if not text:
        return text
    return ZH_EN.get(text, text)

